// Redis Status
export const FETCH_REDIS_STATUS_REQUEST = "FETCH_REDIS_STATUS_REQUEST";
export const FETCH_REDIS_STATUS_SUCCESS = "FETCH_REDIS_STATUS_SUCCESS";
export const FETCH_REDIS_STATUS_FAILURE = "FETCH_REDIS_STATUS_FAILURE";

// Cache Invalidation
export const INVALIDATE_CACHE_REQUEST = "INVALIDATE_CACHE_REQUEST";
export const INVALIDATE_CACHE_SUCCESS = "INVALIDATE_CACHE_SUCCESS";
export const INVALIDATE_CACHE_FAILURE = "INVALIDATE_CACHE_FAILURE";

// Clear All Caches
export const CLEAR_ALL_CACHES_REQUEST = "CLEAR_ALL_CACHES_REQUEST";
export const CLEAR_ALL_CACHES_SUCCESS = "CLEAR_ALL_CACHES_SUCCESS";
export const CLEAR_ALL_CACHES_FAILURE = "CLEAR_ALL_CACHES_FAILURE";

// Redis Keys
export const FETCH_REDIS_KEYS_REQUEST = "FETCH_REDIS_KEYS_REQUEST";
export const FETCH_REDIS_KEYS_SUCCESS = "FETCH_REDIS_KEYS_SUCCESS";
export const FETCH_REDIS_KEYS_FAILURE = "FETCH_REDIS_KEYS_FAILURE";

export const DELETE_REDIS_KEYS_REQUEST = "DELETE_REDIS_KEYS_REQUEST";
export const DELETE_REDIS_KEYS_SUCCESS = "DELETE_REDIS_KEYS_SUCCESS";
export const DELETE_REDIS_KEYS_FAILURE = "DELETE_REDIS_KEYS_FAILURE";

// Redis Info
export const FETCH_REDIS_INFO_REQUEST = "FETCH_REDIS_INFO_REQUEST";
export const FETCH_REDIS_INFO_SUCCESS = "FETCH_REDIS_INFO_SUCCESS";
export const FETCH_REDIS_INFO_FAILURE = "FETCH_REDIS_INFO_FAILURE";

// Flush DB
export const FLUSH_REDIS_DB_REQUEST = "FLUSH_REDIS_DB_REQUEST";
export const FLUSH_REDIS_DB_SUCCESS = "FLUSH_REDIS_DB_SUCCESS";
export const FLUSH_REDIS_DB_FAILURE = "FLUSH_REDIS_DB_FAILURE";

// Pattern Delete
export const DELETE_REDIS_PATTERN_REQUEST = "DELETE_REDIS_PATTERN_REQUEST";
export const DELETE_REDIS_PATTERN_SUCCESS = "DELETE_REDIS_PATTERN_SUCCESS";
export const DELETE_REDIS_PATTERN_FAILURE = "DELETE_REDIS_PATTERN_FAILURE";
