export const FETCH_GSC_OVERVIEW_REQUEST = "FETCH_GSC_OVERVIEW_REQUEST";
export const FETCH_GSC_OVERVIEW_SUCCESS = "FETCH_GSC_OVERVIEW_SUCCESS";
export const FETCH_GSC_OVERVIEW_FAILURE = "FETCH_GSC_OVERVIEW_FAILURE";

export const FETCH_GSC_TRENDS_REQUEST = "FETCH_GSC_TRENDS_REQUEST";
export const FETCH_GSC_TRENDS_SUCCESS = "FETCH_GSC_TRENDS_SUCCESS";
export const FETCH_GSC_TRENDS_FAILURE = "FETCH_GSC_TRENDS_FAILURE";

export const FETCH_GSC_QUERIES_REQUEST = "FETCH_GSC_QUERIES_REQUEST";
export const FETCH_GSC_QUERIES_SUCCESS = "FETCH_GSC_QUERIES_SUCCESS";
export const FETCH_GSC_QUERIES_FAILURE = "FETCH_GSC_QUERIES_FAILURE";

export const FETCH_GSC_PAGES_REQUEST = "FETCH_GSC_PAGES_REQUEST";
export const FETCH_GSC_PAGES_SUCCESS = "FETCH_GSC_PAGES_SUCCESS";
export const FETCH_GSC_PAGES_FAILURE = "FETCH_GSC_PAGES_FAILURE";

export const FETCH_GSC_DEVICES_REQUEST = "FETCH_GSC_DEVICES_REQUEST";
export const FETCH_GSC_DEVICES_SUCCESS = "FETCH_GSC_DEVICES_SUCCESS";
export const FETCH_GSC_DEVICES_FAILURE = "FETCH_GSC_DEVICES_FAILURE";

export const FETCH_GSC_COUNTRIES_REQUEST = "FETCH_GSC_COUNTRIES_REQUEST";
export const FETCH_GSC_COUNTRIES_SUCCESS = "FETCH_GSC_COUNTRIES_SUCCESS";
export const FETCH_GSC_COUNTRIES_FAILURE = "FETCH_GSC_COUNTRIES_FAILURE";

export const FETCH_GSC_OPPORTUNITIES_REQUEST = "FETCH_GSC_OPPORTUNITIES_REQUEST";
export const FETCH_GSC_OPPORTUNITIES_SUCCESS = "FETCH_GSC_OPPORTUNITIES_SUCCESS";
export const FETCH_GSC_OPPORTUNITIES_FAILURE = "FETCH_GSC_OPPORTUNITIES_FAILURE";

export const FETCH_GSC_KEYWORD_GAPS_REQUEST = "FETCH_GSC_KEYWORD_GAPS_REQUEST";
export const FETCH_GSC_KEYWORD_GAPS_SUCCESS = "FETCH_GSC_KEYWORD_GAPS_SUCCESS";
export const FETCH_GSC_KEYWORD_GAPS_FAILURE = "FETCH_GSC_KEYWORD_GAPS_FAILURE";
