services:
  massclick-api-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: massclick-api-dev
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - /var/www/dev-massclick/client/ui-app/build:/var/www/dev-massclick/client/ui-app/build:ro
    network_mode: host
