import React from "react";
import { useNavigate } from "react-router-dom";
import { BadgeCheck, Bookmark, CheckCircle2, ChevronRight, Crown, Download, FilePenLine, FileText, Headphones, Home, Image, LayoutGrid, Palette, Printer, Recycle, Settings, ShieldCheck, Sparkles, Tag, UserRound, Users } from "lucide-react";
import StickySearchBar from "../../StickySearchBar/StickySearchBar";
import { createScopedClassNames } from "../../../../utils/createScopedClassNames";
import styles from "./MarketingMaterialsOverview.module.css";
const cx = createScopedClassNames(styles);

const materials = [
  { type:"visiting-card", title:"Visiting Card", copy:"Professional business cards to make a lasting impression", count:18, icon:UserRound },
  { type:"letterhead", title:"Letterhead", copy:"Official letterheads for your business", count:16, icon:FileText },
  { type:"quotation", title:"Quotation", copy:"Professional quotations that win more business", count:20, icon:FilePenLine },
  { type:"voucher", title:"Voucher", copy:"Attractive vouchers to boost your offers", count:12, icon:Tag },
];
const navItems = [{label:"Overview",icon:Home},{label:"Visiting Card",icon:Users,type:"visiting-card"},{label:"Letterhead",icon:FileText,type:"letterhead"},{label:"Quotation",icon:FilePenLine,type:"quotation"},{label:"Voucher",icon:Tag,type:"voucher"}];
const quickItems = [{label:"My Downloads",icon:Download,route:"/user_massclick-documents"},{label:"Saved Templates",icon:Bookmark,route:"/user_favorites"},{label:"Brand Kit",icon:Palette,route:"/user_edit-profile"},{label:"Settings",icon:Settings,route:"/user_edit-profile"}];
const templates = [{kind:"card",title:"Modern Business Card",flag:"PRO"},{kind:"letterhead",title:"Corporate Letterhead",flag:"NEW"},{kind:"quotation",title:"Professional Quotation"},{kind:"voucher",title:"Gift Voucher",flag:"NEW"}];
const features = [{icon:FilePenLine,title:"Easy to Customize",copy:"Edit in minutes"},{icon:FileText,title:"Multiple Formats",copy:"PDF, PNG, JPG, SVG"},{icon:Printer,title:"Print Ready",copy:"300 DPI Quality"},{icon:Recycle,title:"Save & Reuse",copy:"Your Favorite Designs"},{icon:ShieldCheck,title:"Secure & Private",copy:"Your Data is Safe"}];

const TemplateArt=({kind})=><div className={cx("template-art",`template-${kind}`)} aria-hidden="true"><div className={cx("mock-brand")}><span>M</span><b>YOUR BUSINESS</b><small>YOUR TAGLINE HERE</small></div><i className={cx("mock-line","mock-a")}/><i className={cx("mock-line","mock-b")}/><i className={cx("mock-line","mock-c")}/>{kind==="card"&&<div className={cx("card-person")}><b>John Doe</b><small>Managing Director</small><i/><i/><i/></div>}{kind==="quotation"&&<div className={cx("quote-table")}><b>QUOTATION</b><i/><i/><i/><i/></div>}{kind==="voucher"&&<div className={cx("voucher-copy")}><b>GIFT</b><span>VOUCHER</span><strong>50%<small> DISCOUNT</small></strong></div>}</div>;

export default function MarketingMaterialsOverview(){
 const navigate=useNavigate(); const open=(type)=>navigate(`/user_marketing-materials?type=${type}`);
 return <><StickySearchBar/><div className={cx("workspace")}>
  <aside className={cx("left-nav")}><div className={cx("nav-title")}><Image/> MARKETING MATERIALS</div><nav>{navItems.map(({label,icon:Icon,type})=><button key={label} className={cx(!type&&"active")} onClick={()=>type?open(type):navigate("/user_marketing-materials")}><Icon/>{label}</button>)}</nav><p className={cx("quick-title")}>QUICK ACTIONS</p><nav>{quickItems.map(({label,icon:Icon,route})=><button key={label} onClick={()=>navigate(route)}><Icon/>{label}</button>)}</nav><div className={cx("premium")}><Crown/><h3>Go Premium</h3><p>Unlock all premium templates,<br/>brand kit, and more exciting<br/>features.</p><button onClick={()=>navigate("/user_rewards")}>Upgrade Now <ChevronRight/></button></div></aside>
  <main className={cx("page")}><section className={cx("hero")}><div className={cx("hero-copy")}><p className={cx("eyebrow")}>MARKETING MATERIALS</p><h1>Design. Impress.<br/><em>Grow Your Business.</em></h1><p className={cx("hero-text")}>Professional templates that make your brand<br/>stand out and build trust with your customers.</p><div className={cx("stats")}><span><Sparkles/><b>150+</b><small>Premium Templates</small></span><span><ShieldCheck/><b>100%</b><small>Customizable</small></span><span><BadgeCheck/><b>High Quality</b><small>Print Ready</small></span><span><Download/><b>Instant</b><small>Download</small></span></div></div><div className={cx("hero-art")}><span className={cx("dot-field")}/><div className={cx("plant")}>☘</div><div className={cx("sheet","sheet-main")}><TemplateArt kind="letterhead"/></div><div className={cx("sheet","sheet-card")}><TemplateArt kind="card"/></div><div className={cx("sheet","sheet-small")}><TemplateArt kind="quotation"/></div></div></section>
  <div className={cx("content-grid")}><div className={cx("content")}><section><h2>Choose a Marketing Material</h2><div className={cx("orange-rule")}/><div className={cx("material-grid")}>{materials.map(({type,title,copy,count,icon:Icon},i)=><button key={type} className={cx("material-card",i===0&&"featured")} onClick={()=>open(type)}><span className={cx("material-icon")}><Icon/></span><strong>{title}</strong><p>{copy}</p><span className={cx("card-footer")}>{count} Templates<ChevronRight/></span></button>)}</div></section><section className={cx("popular")}><div className={cx("section-heading")}><div><h2>Popular Templates</h2><div className={cx("orange-rule")}/></div><button onClick={()=>open("visiting-card")}>View All Templates <ChevronRight/></button></div><div className={cx("template-grid")}>{templates.map(({kind,title,flag})=><button key={kind} className={cx("template-card")} onClick={()=>open(kind==="card"?"visiting-card":kind)}>{flag&&<span className={cx("flag")}>{flag}</span>}<TemplateArt kind={kind}/><span className={cx("template-meta")}><b>{title}</b><span><Bookmark/><Download/></span></span></button>)}</div></section><section className={cx("features")}>{features.map(({icon:Icon,title,copy})=><div key={title}><Icon/><span><b>{title}</b><small>{copy}</small></span></div>)}</section></div>
  <aside className={cx("right-nav")}><div className={cx("side-card","benefits")}><h3>Why Choose Our Templates?</h3>{["Professionally Designed","Fully Customizable","Print Ready (300 DPI)","Multiple File Formats","Save Time & Money"].map(x=><span key={x}><CheckCircle2/>{x}</span>)}</div><div className={cx("side-card","help")}><h3>Need Help?</h3><p>Our support team is here to help you create the perfect marketing materials.</p><button onClick={()=>navigate("/user-customer-service")}><Headphones/>Contact Support</button></div><div className={cx("side-card","brand")}><LayoutGrid/><h3>Maintain Brand Consistency</h3><p>Use your brand colors, fonts and logo across all your marketing materials.</p><button onClick={()=>navigate("/user_edit-profile")}>Setup Brand Kit <ChevronRight/></button></div></aside></div></main>
 </div></>;
}
