import express from "express";
import { createHttpAuthMiddleware } from "../auth/authMiddleware.js";
import { allClaimsAction, awardAction, businessLocationsAction, categoryOptionsAction, claimBusinessesAction, createClaimAction, customerClaimsAction, deleteRuleAction, redeemAction, requireAdmin, reviewClaimAction, rewardCatalogAction, rulesAction, saveRuleAction, walletAction } from "../controller/rewards/rewardController.js";
const router = express.Router();
const catalogAuth = createHttpAuthMiddleware({ allowedActorTypes: ["admin", "customer", "publicClient"], source: "rewards-http" });
const walletAuth = createHttpAuthMiddleware({ allowedActorTypes: ["admin", "customer"], source: "rewards-http" });
router.get("/api/rewards/catalog", catalogAuth, rewardCatalogAction);
router.get("/api/rewards/business-locations", businessLocationsAction);
router.get("/api/rewards/businesses", claimBusinessesAction);
router.get("/api/rewards/wallet", walletAuth, walletAction);
router.get("/api/rewards/wallet/:customerKey", walletAuth, walletAction);
router.post("/api/rewards/redeem", walletAuth, redeemAction);
router.post("/api/rewards/claims", walletAuth, createClaimAction);
router.get("/api/rewards/claims/mine", walletAuth, customerClaimsAction);
router.get("/api/rewards/admin/rules", walletAuth, requireAdmin, rulesAction);
router.get("/api/rewards/admin/category-options", walletAuth, requireAdmin, categoryOptionsAction);
router.put("/api/rewards/admin/rules", walletAuth, requireAdmin, saveRuleAction);
router.delete("/api/rewards/admin/rules/:id", walletAuth, requireAdmin, deleteRuleAction);
router.post("/api/rewards/admin/award", walletAuth, requireAdmin, awardAction);
router.get("/api/rewards/admin/claims", walletAuth, requireAdmin, allClaimsAction);
router.patch("/api/rewards/admin/claims/:id", walletAuth, requireAdmin, reviewClaimAction);
export default router;
