import React, { useMemo, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, useNavigate } from "react-router-dom";
import StickySearchBar from "../../StickySearchBar/StickySearchBar";
import { createMassclickFeedPost } from "../../../../redux/actions/massclickFeedAction.js";
import styles from "./SpotlightCreatePage.module.css";
import { Sparkles, PlusCircle, Images, CalendarDays, Send, UserRound, FileText, Settings, Tag, Newspaper, Calendar, Box, Cog, Megaphone, BriefcaseBusiness, BarChart3, Play, UploadCloud, Heart, MessageSquareText, Share2, Bookmark, Lightbulb, Eye } from "lucide-react";

const types = [["offer","Offer / Discount"],["update","Update / News"],["event","Event"],["product","Product"],["service","Service"],["announcement","Announcement"],["job","Job / Hiring"],["poll","Poll / Survey"],["video","Video Post"]];
const audiences = ["Local Customers","New Customers","Students","Families","Business Owners","Fitness Enthusiasts"];
const actionOptions = [["call","Call Now","Phone number"],["whatsapp","WhatsApp","WhatsApp number"],["book","Book Now","Booking URL"],["shop","Shop Now","Shop URL"],["learn","Learn More","Website URL"],["direction","Get Direction","Map or location URL"]];
const MAX_ATTACHMENTS = 4;
const MAX_FILE_SIZE = 45 * 1024 * 1024;
const ACCEPTED_TYPES = ["image/jpeg","image/png","image/webp","video/mp4","video/quicktime","application/pdf","text/plain","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation"];
const readFile = (file) => new Promise((resolve,reject) => { const reader=new FileReader(); reader.onload=()=>resolve(reader.result); reader.onerror=reject; reader.readAsDataURL(file); });

const createNav = [[Sparkles,"Spotlight","/user_feed"],[PlusCircle,"Create Post","/user_spotlight/create"],[Newspaper,"My Posts","/user_feed"],[CalendarDays,"Calendar","/user_spotlight/calendar"],[Send,"Campaigns","/user_spotlight/campaigns"],[UserRound,"Leads","/user_spotlight/leads"],[Images,"Media Library","/user_spotlight/media"],[FileText,"Reports","/user_spotlight/reports"],[Settings,"Settings","/user_dashboard"]];
const typeIcons = { offer:Tag, update:Newspaper, event:Calendar, product:Box, service:Cog, announcement:Megaphone, job:BriefcaseBusiness, poll:BarChart3, video:Play };

function CreateSpotlightReference({form,update,previews,inputRef,addFiles,removeFile,tag,setTag,addTag,user,loading,publish,saveDraft,message}){
  const firstMedia=previews[0];
  const business=user.businessName||user.userName||"Your Business Name";
  return <><StickySearchBar/><main className={styles.referencePage}>
    <aside className={styles.referenceNav}><nav>{createNav.map(([Icon,label,to])=><Link key={label} to={to} className={label==="Create Post"?styles.referenceActive:""}><Icon/><span>{label}</span></Link>)}</nav><section><b>♛</b><h3>Go Premium</h3><p>Unlock advanced tools and grow your business faster.</p><button type="button">Upgrade Now</button></section></aside>
    <section className={styles.referenceEditor}><header><h1>Create Spotlight Post</h1><p>Share offers, updates, events or announcements with the right audience.</p></header>
      <label className={styles.referenceLabel}>Post Type</label><div className={styles.referenceTypes}>{types.map(([key,label])=>{const Icon=typeIcons[key]||Sparkles;return <button type="button" key={key} className={form.postType===key?styles.referenceSelected:""} onClick={()=>update("postType",key)}><i><Icon/></i><span>{label}</span></button>})}</div>
      <label className={styles.referenceLabel}>Headline <small>(Optional)</small></label><div className={styles.referenceInput}><input maxLength={100} value={form.title} onChange={e=>update("title",e.target.value)} placeholder="Add a short headline"/><span>{form.title.length}/100</span></div>
      <label className={styles.referenceLabel}>Your Message <em>*</em></label><div className={styles.referenceMessage}><div><b>B</b><i>I</i><u>U</u><span>☷</span><span>☰</span><span>↗</span><span>▧</span></div><textarea maxLength={1500} value={form.text} onChange={e=>update("text",e.target.value)} placeholder="Write your message here..."/><small>{form.text.length}/1500</small></div>
      <label className={styles.referenceLabel}>Add Media <small>(Optional)</small></label><div className={styles.referenceDrop} onClick={()=>inputRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}>{previews.length?<div className={styles.referenceMedia}>{previews.map((item,index)=><article key={`${item.name}-${index}`}>{item.type.startsWith("video/")?<video src={item.url} controls onClick={e=>e.stopPropagation()}/>:item.type.startsWith("image/")?<img src={item.url} alt={item.name}/>:<FileText/>}<button type="button" onClick={e=>{e.stopPropagation();removeFile(index)}}>×</button></article>)}</div>:<><UploadCloud/><span><strong>Drag and drop files here or click to upload</strong><small>Images, videos or documents (Max 10 MB each)</small></span></>} </div><input ref={inputRef} hidden multiple type="file" accept={ACCEPTED_TYPES.join(",")} onChange={e=>{addFiles(e.target.files);e.target.value=""}}/>
      <label className={styles.referenceLabel}>Add Hashtags <small>(Optional)</small></label><div className={styles.referenceInput}><input value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(e.preventDefault(),addTag())} placeholder="#AddHashtag"/><span>{form.hashtags.length}/5</span></div><div className={styles.referenceTags}>{form.hashtags.slice(0,5).map(value=><button type="button" key={value} onClick={()=>update("hashtags",form.hashtags.filter(item=>item!==value))}>#{value} ×</button>)}</div><small className={styles.referenceHint}>Add up to 5 hashtags to reach more people</small>
      {message&&<div className={styles.referenceError}>{message}</div>}
      <footer><button type="button" disabled={loading} onClick={saveDraft}>Save as Draft</button><button type="button" onClick={()=>document.querySelector(`.${styles.referencePreview}`)?.scrollIntoView({behavior:"smooth"})}><Eye/> Preview</button><button type="button" disabled={loading} onClick={()=>publish(form.scheduledAt?"scheduled":"active")}>{loading?"Publishing…":"Publish Post"}</button></footer>
    </section>
    <aside className={styles.referenceRight}><section className={styles.referencePreview}><header><h2>Live Preview</h2><p>This is how your post will appear to the audience.</p></header><article><div className={styles.referenceAuthor}><b>{business.charAt(0).toUpperCase()}</b><span><strong>{business}</strong><small>Just now · Public</small></span><i>•••</i></div><div className={styles.referencePreviewMedia}>{firstMedia?(firstMedia.type.startsWith("video/")?<video controls src={firstMedia.url}/>:firstMedia.type.startsWith("image/")?<img src={firstMedia.url} alt={firstMedia.name}/>:<FileText/>):<><Images/><span>Your image will appear here</span></>}</div><h3>{form.title||"Your headline will appear here"}</h3><p>{form.text||"Your message will appear here exactly as you write it."}</p>{form.hashtags.length>0&&<div className={styles.referencePreviewTags}>{form.hashtags.slice(0,5).map(value=>`#${value}`).join(" ")}</div>}<nav><button type="button"><Heart/>Interested</button><button type="button"><MessageSquareText/>Enquire</button><button type="button"><Share2/>Share</button><button type="button"><Bookmark/>Save</button></nav><footer><span>🔵 ❤️ 0 Interested</span><span>0 Enquiries</span></footer></article></section>
      <section className={styles.referenceTips}><header><Lightbulb/><h2>Post Tips</h2></header>{["Add a clear headline","Use high quality images","Add relevant hashtags","Keep your message short and engaging"].map(tip=><p key={tip}>✓ {tip}</p>)}</section>
    </aside>
  </main></>;
}

export default function SpotlightCreatePage(){
  const dispatch=useDispatch(); const navigate=useNavigate(); const inputRef=useRef(null); const actionBuilderRef=useRef(null);
  const {loading}=useSelector((state)=>state.massclickFeed||{});
  const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem("authUser")||"{}")}catch{return{}}},[]);
  const [form,setForm]=useState({postType:"update",text:"",title:"",callToActions:[],hashtags:[],audience:["Local Customers","New Customers"],radiusKm:5,scheduledAt:"",expireAfterDays:7,pinPost:false,allowComments:true,showShareButton:true,trackPerformance:true,mediaFiles:[]});
  const [previews,setPreviews]=useState([]); const [tag,setTag]=useState(""); const [message,setMessage]=useState(""); const [previewMode,setPreviewMode]=useState("feed"); const [actionErrors,setActionErrors]=useState({});
  const update=(key,value)=>setForm((old)=>({...old,[key]:value}));
  const addFiles=async(files)=>{const incoming=Array.from(files||[]);const remaining=MAX_ATTACHMENTS-form.mediaFiles.length;if(!remaining){setMessage(`You can attach up to ${MAX_ATTACHMENTS} files.`);return;}const selected=incoming.slice(0,remaining);if(selected.some(f=>f.size>MAX_FILE_SIZE)){setMessage("Each attachment must be 45 MB or smaller.");return;}if(selected.some(f=>!ACCEPTED_TYPES.includes(f.type))){setMessage("Use images, MP4/MOV videos, PDF, Word, Excel, PowerPoint, or text files.");return;}const data=await Promise.all(selected.map(async file=>({mediaFile:await readFile(file),fileName:file.name,fileType:file.type,fileSize:file.size})));setForm(old=>({...old,mediaFiles:[...old.mediaFiles,...data]}));setPreviews(old=>[...old,...data.map(item=>({url:item.mediaFile,type:item.fileType,name:item.fileName,size:item.fileSize}))]);setMessage(incoming.length>remaining?`Only ${remaining} more attachment${remaining===1?" is":"s are"} allowed.`:"");};
  const removeFile=(index)=>{setForm(old=>({...old,mediaFiles:old.mediaFiles.filter((_,i)=>i!==index)}));setPreviews(old=>old.filter((_,i)=>i!==index));if(inputRef.current)inputRef.current.value="";};
  const moveFile=(index,direction)=>{const target=index+direction;if(target<0||target>=previews.length)return;const swap=(items)=>{const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next;};setPreviews(swap);setForm(old=>({...old,mediaFiles:swap(old.mediaFiles)}));};
  const formatSize=(bytes=0)=>bytes>=1048576?`${(bytes/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;
  const addTag=()=>{const clean=tag.trim().replace(/^#/,"");if(clean&&!form.hashtags.includes(clean))update("hashtags",[...form.hashtags,clean].slice(0,5));setTag("")};
  const strength=Math.min(100,25+(form.text.trim()?25:0)+(form.title.trim()?10:0)+(form.mediaFiles.length?15:0)+(form.callToActions.length?10:0)+(form.hashtags.length?5:0)+(form.audience.length?10:0));
  const publish=async(status="active")=>{setMessage("");setActionErrors({});if(!form.text.trim()&&!form.title.trim()&&!form.mediaFiles.length){setMessage("Add post content, a headline, or media before continuing.");return;}const errors={};form.callToActions.forEach(item=>{const value=item.value.trim();if(!value)errors[item.action]=`${item.label} requires ${["call","whatsapp"].includes(item.action)?"a phone number":"a destination URL"}.`;else if(["call","whatsapp"].includes(item.action)&&value.replace(/\D/g,"").length<7)errors[item.action]=`Enter a valid phone number for ${item.label}.`;else if(!["call","whatsapp"].includes(item.action)&&!/^https?:\/\//i.test(value)&&!/^([a-z0-9-]+\.)+[a-z]{2,}(\/.*)?$/i.test(value))errors[item.action]=`Enter a valid website address for ${item.label}.`;});if(Object.keys(errors).length){setActionErrors(errors);setMessage(Object.values(errors)[0]);actionBuilderRef.current?.scrollIntoView({behavior:"smooth",block:"center"});return;}const callToActions=form.callToActions.map(item=>["call","whatsapp"].includes(item.action)?item:{...item,value:/^https?:\/\//i.test(item.value)?item.value:`https://${item.value}`});try{await dispatch(createMassclickFeedPost({...form,callToActions,status}));localStorage.removeItem("spotlightDraft");navigate("/user_feed")}catch(error){setMessage(error.response?.data?.message||error.message||"Unable to save post.")}};
  const saveDraft=()=>{localStorage.setItem("spotlightDraft",JSON.stringify({...form,mediaFiles:[]}));publish("draft")};
  const toggleAudience=(name)=>update("audience",form.audience.includes(name)?form.audience.filter(x=>x!==name):[...form.audience,name]);
  const toggleAction=(action,label)=>{const exists=form.callToActions.some(item=>item.action===action);if(exists){update("callToActions",form.callToActions.filter(item=>item.action!==action));setActionErrors(old=>({...old,[action]:""}));setMessage("");return}if(form.callToActions.length>=3){setMessage("Choose up to three call-to-action buttons.");return}const isPhone=action==="call"||action==="whatsapp";const value=isPhone?(user.whatsappNumber||user.mobileNumber1||user.mobile||user.contact||""):(user.website||user.websiteUrl||"");update("callToActions",[...form.callToActions,{action,label,value}]);};
  const setActionValue=(action,value)=>{update("callToActions",form.callToActions.map(item=>item.action===action?{...item,value}:item));setActionErrors(old=>({...old,[action]:""}));setMessage("");};
  return <CreateSpotlightReference form={form} update={update} previews={previews} inputRef={inputRef} addFiles={addFiles} removeFile={removeFile} tag={tag} setTag={setTag} addTag={addTag} user={user} loading={loading} publish={publish} saveDraft={saveDraft} message={message}/>;
  // eslint-disable-next-line no-unreachable
  if(false) return <><StickySearchBar/><main className={styles.page}>
    <aside>{[["✦","Spotlight","/user_feed"],["＋","Create","/user_spotlight/create"],["▣","My Posts","/user_feed"],["□","Calendar","/user_spotlight/calendar"],["◁","Campaigns","/user_spotlight/campaigns"],["♙","Leads","/user_spotlight/leads"],["▧","Media","/user_spotlight/media"],["▥","Reports","/user_spotlight/reports"],["⚙","Settings","/user_dashboard"]].map(([icon,label,to])=><Link className={label==="Create"?styles.active:""} to={to} key={label}><i>{icon}</i><span>{label}</span></Link>)}</aside>
    <header><div><h1>Create Spotlight</h1><p>Create engaging posts to promote your business and connect with local customers.</p></div><div className={styles.headerActions}><button onClick={saveDraft}>Save as Draft</button><button onClick={()=>setPreviewMode(previewMode==="feed"?"profile":"feed")}>◉ Preview</button><button className={styles.publish} disabled={loading} onClick={()=>publish(form.scheduledAt?"scheduled":"active")}>{loading?"Publishing…":form.scheduledAt?"Schedule Post":"Publish Now"}</button><Link to="/user_feed">×</Link></div></header>
    <div className={styles.columns}><section className={styles.editor}>
      <Card n="1" title="Create Your Post" sub="Add your content and organize your post details."><label>Post Type</label><div className={styles.typeGrid}>{types.map(([key,label])=><button className={form.postType===key?styles.selected:""} onClick={()=>update("postType",key)} key={key}>{label}</button>)}</div><label>Post Content</label><div className={styles.toolbar}>B　<i>I</i>　<u>U</u>　☷　☰　🔗　☺　▧</div><textarea maxLength={2500} value={form.text} onChange={e=>update("text",e.target.value)} placeholder="Write your update, announcement, or any message for your customers…"/><small className={styles.counter}>{form.text.length}/2500</small><Field label="Optional Headline"><input maxLength={100} value={form.title} onChange={e=>update("title",e.target.value)} placeholder="Add a short headline (optional)"/></Field><div className={styles.actionBuilder} ref={actionBuilderRef}><div className={styles.actionTitle}><strong>Call To Actions</strong><small>Select up to 3 actions</small></div><div className={styles.actionChoices}>{actionOptions.map(([action,label])=><button type="button" className={form.callToActions.some(item=>item.action===action)?styles.actionSelected:""} onClick={()=>toggleAction(action,label)} key={action}>{form.callToActions.some(item=>item.action===action)?"✓ ":"＋ "}{label}</button>)}</div>{form.callToActions.map(item=>{const option=actionOptions.find(([action])=>action===item.action);return <label className={`${styles.actionDestination} ${actionErrors[item.action]?styles.actionInvalid:""}`} key={item.action}><span>{item.label}</span><div><input aria-invalid={Boolean(actionErrors[item.action])} value={item.value} onChange={e=>setActionValue(item.action,e.target.value)} placeholder={option?.[2]||"Destination"}/>{actionErrors[item.action]&&<small>{actionErrors[item.action]}</small>}</div></label>})}</div></Card>
      <Card n="2" title="Add Media & Attachments" sub="Add up to four images, videos, or business documents."><div className={styles.mediaActions}><button type="button" onClick={()=>inputRef.current?.click()}>＋ Upload Files</button><Link to="/user_spotlight/media">Media Library</Link><button type="button" onClick={()=>inputRef.current?.click()}>Create with Template</button></div><input hidden ref={inputRef} multiple type="file" accept={ACCEPTED_TYPES.join(",")} onChange={e=>{addFiles(e.target.files);e.target.value="";}}/><div className={styles.uploadSummary}><span><strong>{form.mediaFiles.length}</strong> / {MAX_ATTACHMENTS} selected</span><small>Images, video and documents · 45 MB each</small></div><div className={styles.drop} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add(styles.dragging)}} onDragLeave={e=>e.currentTarget.classList.remove(styles.dragging)} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove(styles.dragging);addFiles(e.dataTransfer.files)}} onClick={()=>!previews.length&&inputRef.current?.click()}>{previews.length?<div className={styles.previewTiles}>{previews.map((p,i)=><article className={styles.mediaTile} key={`${p.name}-${i}`}>{p.type.startsWith("video/")?<video controls src={p.url} onClick={e=>e.stopPropagation()}/>:p.type.startsWith("image/")?<img src={p.url} alt={p.name}/>:<div className={styles.filePreview}><b>{p.name.split(".").pop()?.toUpperCase()}</b><span>Document</span></div>}<div className={styles.mediaMeta}><strong title={p.name}>{p.name}</strong><small>{formatSize(p.size)}</small></div><div className={styles.mediaControls}><button type="button" onClick={e=>{e.stopPropagation();moveFile(i,-1)}} disabled={!i} aria-label="Move attachment left">←</button><button type="button" onClick={e=>{e.stopPropagation();moveFile(i,1)}} disabled={i===previews.length-1} aria-label="Move attachment right">→</button><button type="button" className={styles.removeMedia} onClick={e=>{e.stopPropagation();removeFile(i)}} aria-label={`Remove ${p.name}`}>×</button></div>{i===0&&<span className={styles.coverBadge}>Cover</span>}</article>)}</div>:<><span className={styles.uploadIcon}>⇧</span><strong>Drop 2–3 photos, videos, or files here</strong><small>JPG, PNG, WebP, MP4, MOV, PDF and Office files</small><button type="button">Browse files</button></>}</div>{previews.length>0&&form.mediaFiles.length<MAX_ATTACHMENTS&&<button type="button" className={styles.addMore} onClick={()=>inputRef.current?.click()}>＋ Add another attachment</button>}</Card>
      <Card n="3" title="Location & Audience" sub="Choose where and who should see your post."><div className={styles.three}><Field label="Add Location"><label><input type="radio" checked readOnly/> My Business Location</label><small>{user.businessLocation||user.location||"Business location"}</small><label><input type="radio"/> Custom Area</label></Field><Field label="Radius"><select value={form.radiusKm} onChange={e=>update("radiusKm",Number(e.target.value))}>{[1,5,10,25,50].map(v=><option value={v} key={v}>Within {v} KM</option>)}</select></Field><Field label="Target Audience">{audiences.map(name=><label key={name}><input type="checkbox" checked={form.audience.includes(name)} onChange={()=>toggleAudience(name)}/>{name}</label>)}</Field></div></Card>
      <Card n="4" title="Post Settings" sub="Set visibility, schedule and more options."><div className={styles.settings}><Field label="Visibility"><select><option>Public</option></select></Field><Field label="Schedule"><input type="datetime-local" value={form.scheduledAt} onChange={e=>update("scheduledAt",e.target.value)}/></Field><Field label="Expire After"><select value={form.expireAfterDays} onChange={e=>update("expireAfterDays",e.target.value)}><option value="">Never</option><option value="1">1 Day</option><option value="7">7 Days</option><option value="30">30 Days</option></select></Field></div></Card>{message&&<div className={styles.message}>{message}</div>}<section className={styles.bottomPublish}><div><strong>{form.scheduledAt?"Ready to schedule your Spotlight?":"Ready to publish your Spotlight?"}</strong><p>Review the preview, then save a draft or publish when everything looks right.</p></div><div><button type="button" onClick={saveDraft} disabled={loading}>Save as Draft</button><button type="button" onClick={()=>setPreviewMode(previewMode==="feed"?"profile":"feed")}>◉ Preview</button><button type="button" className={styles.bottomPrimary} disabled={loading} onClick={()=>publish(form.scheduledAt?"scheduled":"active")}>{loading?"Saving…":form.scheduledAt?"Schedule Post":"Publish Post"}</button></div></section>
    </section><section className={styles.live}><div className={styles.panel}><h2>Live Preview</h2><p>See how your complete post will appear to your audience.</p><div className={styles.previewTabs}><button className={previewMode==="feed"?styles.selected:""} onClick={()=>setPreviewMode("feed")}>Feed Preview</button><button className={previewMode==="profile"?styles.selected:""} onClick={()=>setPreviewMode("profile")}>Profile Preview</button></div><article className={`${styles.postPreview} ${previewMode==="profile"?styles.profilePreview:""}`}><header><b>{(user.businessName||user.userName||"B").charAt(0)}</b><span><strong>{user.businessName||user.userName||"Your Business"}</strong><small>{user.businessLocation||"Business location"} · Just now</small></span></header><h3>{form.title||"Your headline will appear here (optional)"}</h3><p>{form.text||"Your post content will appear here exactly as you write it."}</p>{previews.length?<div className={`${styles.liveMediaGrid} ${styles[`liveMedia${Math.min(previews.length,4)}`]}`}>{previews.map((item,index)=>item.type.startsWith("video/")?<video controls src={item.url} key={`${item.name}-${index}`}/>:item.type.startsWith("image/")?<img src={item.url} alt={item.name} key={`${item.name}-${index}`}/>:<a href={item.url} download={item.name} className={styles.liveFile} key={`${item.name}-${index}`}><b>{item.name.split(".").pop()?.toUpperCase()}</b><span>{item.name}</span><small>{formatSize(item.size)}</small></a>)}</div>:<div className={styles.noMedia}>▧<span>No media added</span></div>}<div className={styles.previewActions}>{form.callToActions.map(item=><button className={styles.cta} type="button" key={item.action}>{item.label}</button>)}</div><footer>♡ Like　　□ Comment　　↗ Share　　♧ Save</footer></article></div><div className={styles.panel}><h2>Post Check List</h2><div className={styles.checks}>{[[form.text||form.title,"Content Added"],[form.mediaFiles.length,"Media Added"],[form.callToActions.length,"Call To Action Selected"],[form.audience.length,"Audience Selected"],[form.hashtags.length,"Hashtags Added"],[form.audience.length&&Boolean(form.text||form.title||form.mediaFiles.length),"Ready to Publish"]].map(([ok,label])=><span className={ok?styles.done:""} key={label}>{ok?"✓":"−"} {label}</span>)}</div></div></section>
    <section className={styles.right}><div className={styles.panel}><h2>Post Strength</h2><div className={styles.gauge} style={{"--score":`${strength*1.8}deg`}}><strong>{strength}/100</strong><span>{strength>75?"Excellent":strength>55?"Good":"Needs work"}</span></div><ul><li className={form.mediaFiles.length?styles.ok:""}>Add media to increase engagement</li><li className={form.hashtags.length?styles.ok:""}>Add relevant hashtags</li><li className={form.text?styles.ok:""}>Your content looks good</li><li className={form.callToActions.length?styles.ok:""}>Call to action is added</li></ul></div><div className={styles.panel}><h2>Suggested Hashtags</h2><div className={styles.tags}>{form.hashtags.map(t=><button onClick={()=>update("hashtags",form.hashtags.filter(x=>x!==t))} key={t}>#{t} ×</button>)}</div><div className={styles.tagInput}><input value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(e.preventDefault(),addTag())} placeholder="Add a hashtag"/><button onClick={addTag}>＋</button></div></div><div className={styles.panel}><h2>Additional Options</h2>{[["pinPost","Pin Post"],["allowComments","Allow Comments"],["showShareButton","Show Share Button"],["trackPerformance","Track Performance"]].map(([key,label])=><label className={styles.switchRow} key={key}><span><strong>{label}</strong></span><input type="checkbox" checked={form[key]} onChange={e=>update(key,e.target.checked)}/><i/></label>)}</div></section></div>
  </main></>;
}
function Card({n,title,sub,children}){return <section className={styles.card}><header><b>{n}</b><div><h2>{title}</h2><p>{sub}</p></div></header>{children}</section>}
function Field({label,children}){return <div className={styles.field}><strong>{label}</strong>{children}</div>}
