export const Collections = {
    USER: 'user',
    OAUTHUSERS: 'oauthusers',
    CLIENT: 'clients',
    USERCLIENT: 'userclient',
    LOCATION: 'location',
    CATEGORY: 'category',
    BUSINESSLIST: 'businesslist',
    ROLES: 'roles',
    LOGSEARCH: 'logsearch',
    ENQUIRY: 'enquiry',
    STARTPROJECT: 'startproject',
    MESSAGE91: 'message91',
    MSG91WHATSAPPAUDIT: 'msg91_whatsapp_audits',
    MSG91RECIPIENTHEALTH: 'msg91_recipient_healths',
    MSGUSERS: 'msgusers',
    LOCATIONIP: 'locationip',
    PAYMENT: 'payment',
    ADVERTISMENTS: 'advertisments',
    SEODATAS: 'seodatas',
    SEOPAGECONTENT: 'seopagecontent',
    SEOPAGECONTENTBLOG: 'seopagecontentblog',
    AUTHORMASTER: 'authormasters',
    MRPDATAS: 'mrpdatas',
    ENQUIRYNOWDATAS: 'enquirynowdatas',
    BUSINESSREVIEW: 'businessreview',
    LEADROTATION: 'leadsrotation',
    PUBLICIZE: 'publicize',
    TERMSANDCONDITIONS: 'termsandconditions',
    FAVORITES: 'favorites',
    FCMCAMPAIGNS: 'fcmcampaigns',
    SYSTEMSETTINGS: 'systemsettings',
    CATEGORYDISPLAYSETTINGS: 'categorydisplaysettings',
    EVENTCATEGORY: 'eventcategory',
    EVENTLOCATION: 'eventlocation',
    EVENTADVERTISEMENT: 'eventadvertisement',
    EVENTCREATION: 'eventcreation',
    GMAPSLEADS: 'gmaps_leads',
    CHATCONVERSATION: 'chatconversations',
    CHATMESSAGE: 'chatmessages',
    BUSINESSWEBPMIGRATIONJOB: 'business_webp_migration_jobs'
};

export const {
    USER,
    OAUTHUSERS,
    CLIENT,
    USERCLIENT,
    LOCATION,
    CATEGORY,
    BUSINESSLIST,
    ROLES,
    LOGSEARCH,
    ENQUIRY,
    STARTPROJECT,
    MESSAGE91,
    MSG91WHATSAPPAUDIT,
    MSG91RECIPIENTHEALTH,
    MSGUSERS,
    LOCATIONIP,
    PAYMENT,
    ADVERTISMENTS,
    SEODATAS,
    SEOPAGECONTENT,
    SEOPAGECONTENTBLOG,
    AUTHORMASTER,
    MRPDATAS,
    ENQUIRYNOWDATAS,
    BUSINESSREVIEW,
    LEADROTATION,
    PUBLICIZE,
    TERMSANDCONDITIONS,
    FAVORITES,
    FCMCAMPAIGNS,
    SYSTEMSETTINGS,
    CATEGORYDISPLAYSETTINGS,
    EVENTCATEGORY,
    EVENTLOCATION,
    EVENTADVERTISEMENT,
    EVENTCREATION,
    GMAPSLEADS,
    CHATCONVERSATION,
    CHATMESSAGE,
    BUSINESSWEBPMIGRATIONJOB
} = Collections;
