export const Collections = {
    USER: 'user',
    OAUTHUSERS: 'oauthusers',
    CLIENT: 'clients',
    USERCLIENT: 'userclient',
    LOCATION: 'location',
    CATEGORY: 'category',
    BUSINESSLIST: 'businesslist',
    ROLES: 'roles',
    LOGSEARCH: 'logsearch',
    ENQUIRY: 'enquiry',
    STARTPROJECT: 'startproject',
    MESSAGE91: 'message91',
    MSGUSERS: 'msgusers',
    LOCATIONIP: 'locationip',
    PAYMENT: 'payment',
    ADVERTISMENTS: 'advertisments',
    SEODATAS: 'seodatas',
    SEOPAGECONTENT: 'seopagecontent',
    SEOPAGECONTENTBLOG: 'seopagecontentblog',
    MRPDATAS: 'mrpdatas',
    ENQUIRYNOWDATAS: 'enquirynowdatas',
    BUSINESSREVIEW: 'businessreview',
    LEADROTATION: 'leadsrotation',
    ADVERTISE: 'advertise',
    TERMSANDCONDITIONS: 'termsandconditions',
    FAVORITES: 'favorites',
    FCMCAMPAIGNS: 'fcmcampaigns',
    SYSTEMSETTINGS: 'systemsettings'
};

export const {
    USER,
    OAUTHUSERS,
    CLIENT,
    USERCLIENT,
    LOCATION,
    CATEGORY,
    BUSINESSLIST,
    ROLES,
    LOGSEARCH,
    ENQUIRY,
    STARTPROJECT,
    MESSAGE91,
    MSGUSERS,
    LOCATIONIP,
    PAYMENT,
    ADVERTISMENTS,
    SEODATAS,
    SEOPAGECONTENT,
    SEOPAGECONTENTBLOG,
    MRPDATAS,
    ENQUIRYNOWDATAS,
    BUSINESSREVIEW,
    LEADROTATION,
    ADVERTISE,
    TERMSANDCONDITIONS,
    FAVORITES,
    FCMCAMPAIGNS,
    SYSTEMSETTINGS
} = Collections;