import { lazy } from "react";

export const AdminPages = {
  Dashboard: lazy(() => import(/* webpackChunkName: "admin-dashboard" */ "app/layout/AdminDashboardLayout.js")),
  Login: lazy(() => import(/* webpackChunkName: "admin-login" */ "features/admin/auth/LoginPage.js")),
  User: lazy(() => import(/* webpackChunkName: "admin-users" */ "features/admin/users/Users.js")),
  Clients: lazy(() => import(/* webpackChunkName: "admin-clients" */ "features/admin/clients/Client.js")),
  Business: lazy(() => import(/* webpackChunkName: "admin-business" */ "features/admin/business/Business.js")),
  Category: lazy(() => import(/* webpackChunkName: "admin-category" */ "features/admin/categories/Category.js")),
  Roles: lazy(() => import(/* webpackChunkName: "admin-roles" */ "features/admin/roles/Roles.js")),
  Location: lazy(() => import(/* webpackChunkName: "admin-location" */ "features/admin/location/Location.js")),
  MasterLocation: lazy(() => import(/* webpackChunkName: "admin-master-location" */ "features/admin/location/MasterLocation.js")),
  LocationCoverage: lazy(() => import(/* webpackChunkName: "admin-location-coverage" */ "features/admin/location-coverage/LocationCoverage.js")),
  TermsAndConditionsDatas: lazy(() => import(/* webpackChunkName: "admin-terms" */ "features/admin/footer-content/terms-and-conditions/TermsAndConditionsAdminPage.js")),
  LegalDocuments: lazy(() => import(/* webpackChunkName: "admin-legal-documents" */ "features/admin/legal-documents/LegalDocumentsPage.js")),
  MainGrid: lazy(() => import(/* webpackChunkName: "admin-maingrid" */ "shared/components/MainGrid.js")),
  EnquiryPage: lazy(() => import(/* webpackChunkName: "admin-enquiry" */ "features/admin/enquiries/EnquiryPage.js")),
  SearchRequestsAdmin: lazy(() => import(/* webpackChunkName: "admin-search-requests" */ "features/admin/search-requests/SearchRequestsAdmin.js")),
  RewardAdmin: lazy(() => import(/* webpackChunkName: "admin-rewards" */ "features/admin/rewards/RewardAdmin.js")),
  RewardsConceptPage: lazy(() => import(/* webpackChunkName: "admin-rewards-concept" */ "features/admin/rewards/RewardsConceptPage.js")),
  RewardClaimsAdmin: lazy(() => import(/* webpackChunkName: "admin-reward-claims" */ "features/admin/rewards/RewardClaimsAdmin.js")),
  AdminCustomerCareChat: lazy(() => import(/* webpackChunkName: "admin-customer-care-chat" */ "features/admin/customer-care-chat/AdminCustomerCareChat.js")),
  AdvertisementPage: lazy(() => import(/* webpackChunkName: "admin-advertisement" */ "features/admin/advertisement/AdvertisementPage.js")),
  EventCategory: lazy(() => import(/* webpackChunkName: "admin-event-category" */ "shared/components/eventCategory/eventCategory.js")),
  EventLocation: lazy(() => import(/* webpackChunkName: "admin-event-location" */ "shared/components/eventLocation/eventLocation.js")),
  EventAdvertisement: lazy(() => import(/* webpackChunkName: "admin-event-advertisement" */ "shared/components/eventAdvertisement/eventAdvertisement.js")),
  EventCreation: lazy(() => import(/* webpackChunkName: "admin-event-creation" */ "shared/components/eventCreation/eventCreation.js")),
  MassclickEvent: lazy(() => import(/* webpackChunkName: "admin-massclick-events" */ "features/admin/massclick-events/MassclickEventsAdminPage.js")),
  SeoData: lazy(() => import(/* webpackChunkName: "admin-seo" */ "features/admin/seo/seoData.js")),
  SeoPageContent: lazy(() => import(/* webpackChunkName: "admin-seo-content" */ "features/admin/seo/seoPageContent/seoPageContent.js")),
  SeoPageContentBlogs: lazy(() => import(/* webpackChunkName: "admin-seo-blogs" */ "features/admin/seo/seoPageContentBlog/seoPageContentBlog.js")),
  SeoTemplate: lazy(() => import(/* webpackChunkName: "admin-seo-templates" */ "features/admin/seo/seoTemplate/seoTemplate.js")),
  AuthorMaster: lazy(() => import(/* webpackChunkName: "admin-author-master" */ "features/admin/seo/authorMaster/authorMaster.js")),
  AdminDataAnalytics: lazy(() => import(/* webpackChunkName: "admin-data-analytics" */ "features/admin/analytics/admin-data-analytics/AdminDataAnalytics.js")),
  UnifiedAnalytics: lazy(() => import(/* webpackChunkName: "admin-unified-analytics" */ "features/admin/analytics/unified-analytics/UnifiedAnalytics.js")),
  SiteAnalytics: lazy(() => import(/* webpackChunkName: "admin-site-analytics" */ "features/admin/analytics/site-analytics/SiteAnalytics.js")),
  AppAnalytics: lazy(() => import(/* webpackChunkName: "admin-app-analytics" */ "features/admin/analytics/site-analytics/AppAnalytics.js")),
  BusinessPersonReport: lazy(() => import(/* webpackChunkName: "admin-business-person-report" */ "features/admin/business-person-report/BusinessPersonReport.js")),
  MRPDatas: lazy(() => import(/* webpackChunkName: "admin-mrp" */ "features/admin/mni-data/MniDataPage.js")),
  FCMMarketing: lazy(() => import(/* webpackChunkName: "admin-fcm" */ "features/admin/fcm-marketing/FCMMarketing.js")),
  SystemSettings: lazy(() => import(/* webpackChunkName: "admin-settings" */ "features/admin/system-settings/SystemSettings.js")),
  CategoryDisplaySettings: lazy(() => import(/* webpackChunkName: "admin-cat-display" */ "features/admin/category-display-settings/CategoryDisplaySettings.js")),
  GmapsLeads: lazy(() => import(/* webpackChunkName: "admin-gmaps-leads" */ "features/admin/gmaps-leads/GmapsLeads.js")),
  BusinessDuplicates: lazy(() => import(/* webpackChunkName: "admin-business-duplicates" */ "features/admin/business-duplicates/BusinessDuplicates.js")),
  Msg91Analytics: lazy(() => import(/* webpackChunkName: "admin-msg91-analytics" */ "features/admin/msg91-analytics/Msg91Analytics.js")),
  AuthControl: lazy(() => import(/* webpackChunkName: "admin-auth-console" */ "features/admin/auth-control/AuthControl.js")),
  PublicUserCounterAdmin: lazy(() => import(/* webpackChunkName: "admin-public-user-counter" */ "features/admin/public-user-counter/PublicUserCounterAdmin.js")),
  HiringAdmin: lazy(() => import(/* webpackChunkName: "admin-hiring" */ "features/admin/hiring/HiringAdmin.js")),
  GscAnalytics: lazy(() => import(/* webpackChunkName: "admin-gsc" */ "features/admin/gsc-analytics/GscAnalyticsPage.js")),
  Ga4Analytics: lazy(() => import(/* webpackChunkName: "admin-ga4" */ "features/admin/ga4-analytics/Ga4AnalyticsPage.js")),
  Quotation: lazy(() => import(/* webpackChunkName: "admin-quotation" */ "features/admin/quotation/Quotation.js")),
  MassclickDocuments: lazy(() => import(/* webpackChunkName: "admin-documents" */ "features/admin/massclick-documents/MassclickDocumentsAdminPage.js")),
  MassclickFeedAdmin: lazy(() => import(/* webpackChunkName: "admin-feed" */ "features/admin/massclick-feed/MassclickFeedAdminPage.js")),
};

export const PublicPages = {
  BusinessListing: lazy(() => import(/* webpackChunkName: "home" */ "features/public/HomePage.js")),
  BusinessDetails: lazy(() => import(/* webpackChunkName: "business-detail" */ "features/public/cards/cardDetails.js")),
  EventCarousel: lazy(() => import(/* webpackChunkName: "events" */ "features/public/events/eventCarousel/eventCarousel.js")),
  EventDetails: lazy(() => import(/* webpackChunkName: "event-detail" */ "features/public/events/eventDetails/eventDetails.js")),
  WriteReviewPage: lazy(() => import(/* webpackChunkName: "review" */ "features/public/rating/SubmitReviewPage.js")),
  PaymentStatus: lazy(() => import(/* webpackChunkName: "payment" */ "features/public/payments/PaymentStatusPage.js")),
  LeadsPage: lazy(() => import(/* webpackChunkName: "leads" */ "features/public/leads/LeadsPage.js")),
  PublicizePage: lazy(() => import(/* webpackChunkName: "publicize" */ "features/public/publicize/publicize.js")),
  FreeListingPage: lazy(() => import(/* webpackChunkName: "free-listing" */ "features/public/free-listing/FreeListingPage.js")),
  LeadsCardHistory: lazy(() => import(/* webpackChunkName: "leads-history" */ "features/public/leads/lead-history/LeadHistoryPage.js")),
  BusinessEnquiry: lazy(() => import(/* webpackChunkName: "business-enquiry" */ "features/public/business-enquiry/BusinessEnquiryPage.js")),
  AuthorProfile: lazy(() => import(/* webpackChunkName: "author-profile" */ "features/public/author-profile/AuthorProfilePage.js")),
  RewardClaimPage: lazy(() => import(/* webpackChunkName: "reward-claim" */ "features/public/rewards/RewardClaimPage.js")),
  MassclickEventDetails: lazy(() => import(/* webpackChunkName: "massclick-event-detail" */ "features/public/massclick-events/MassclickEventDetails.js")),
  DistrictRouteResolver: lazy(() => import(/* webpackChunkName: "district-route-resolver" */ "features/public/categories/DistrictRouteResolver.js")),
  CategoriesPage: lazy(() => import(/* webpackChunkName: "category-directory" */ "features/public/categories/categories.js")),
  BlogDetail: lazy(() => import(/* webpackChunkName: "blog-detail" */ "features/public/related-blogs/blogDetails/blogDetails.js")),
  Profile: lazy(() => import(/* webpackChunkName: "profile" */ "features/admin/auth/profile/ProfilePage.js")),
};

export const FooterPages = {
  AboutUsPage: lazy(() => import(/* webpackChunkName: "footer-aboutus" */ "features/public/footer/about-us/AboutUsPage.js")),
  Testimonials: lazy(() => import(/* webpackChunkName: "footer-testimonials" */ "features/public/footer/testimonials/testimonials.js")),
  FeedbackComponent: lazy(() => import(/* webpackChunkName: "footer-feedback" */ "features/public/footer/feedback/feedback.js")),
  CustomerCareComponent: lazy(() => import(/* webpackChunkName: "footer-care" */ "features/public/footer/customer-care/customerCare.js")),
  Portfolio: lazy(() => import(/* webpackChunkName: "footer-portfolio" */ "features/public/footer/portfolio/portfolio.js")),
  TermsAndConditions: lazy(() => import(/* webpackChunkName: "footer-terms" */ "features/public/footer/terms-and-conditions/termsAndCondition.js")),
  PrivacyPolicy: lazy(() => import(/* webpackChunkName: "footer-privacy" */ "features/public/footer/privacy-policy/privacyPolicy.js")),
  RefundPolicy: lazy(() => import(/* webpackChunkName: "footer-refund" */ "features/public/footer/refund/refundPolicy.js")),
  EnquiryNow: lazy(() => import(/* webpackChunkName: "footer-enquiry" */ "features/public/footer/enquiry/enquiry.js")),
  WebDevSection: lazy(() => import(/* webpackChunkName: "footer-webdev" */ "features/public/footer/web-dev/webDevSection.js")),
  DigitalMarketing: lazy(() => import(/* webpackChunkName: "footer-digital" */ "features/public/footer/digital-marketing/digitalMarketing.js")),
  GraphicDesign: lazy(() => import(/* webpackChunkName: "footer-graphic" */ "features/public/footer/graphic-design/graphicDesign.js")),
  Seo: lazy(() => import(/* webpackChunkName: "footer-seo" */ "features/public/footer/seo/seo.js")),
  DeleteAccount: lazy(() => import(/* webpackChunkName: "footer-delete" */ "features/public/footer/delete-account/deleteAccount.js")),
  KnowledgeBasePage: lazy(() => import(/* webpackChunkName: "knowledge-base" */ "features/public/footer/knowledge-base/knowledgeBase.js")),
  CareersPage: lazy(() => import(/* webpackChunkName: "footer-careers" */ "features/public/footer/careers/CareersPage.js")),
  JobResultsPage: lazy(() => import(/* webpackChunkName: "careers-jobs" */ "features/public/footer/careers/JobResultsPage.js")),
  JobApplicationPage: lazy(() => import(/* webpackChunkName: "careers-apply" */ "features/public/footer/careers/JobApplicationPage.js")),
};

export const UserPages = {
  UserDashboardPage: lazy(() => import(/* webpackChunkName: "user-dashboard" */ "features/user/dashboard/UserDashboardPage.js")),
  UserEditProfilePage: lazy(() => import(/* webpackChunkName: "user-edit-profile" */ "features/user/edit-profile/EditProfilePage.js")),
  UserMRPPage: lazy(() => import(/* webpackChunkName: "user-mni" */ "features/public/mrp/mrp.js")),
  UserMarketingMaterialsPage: lazy(() => import(/* webpackChunkName: "user-marketing-materials" */ "features/user/marketing-materials/MarketingMaterialsPage.js")),
  UserFavoritesPage: lazy(() => import(/* webpackChunkName: "user-favorites" */ "features/user/favorites/FavoritesPage.js")),
  UserCustomerServicePage: lazy(() => import(/* webpackChunkName: "user-customer-service" */ "features/user/customer-service/CustomerServicePage.js")),
  UserPolicyPage: lazy(() => import(/* webpackChunkName: "user-policy" */ "features/user/policy/PolicyPage.js")),
  UserFeedbackPage: lazy(() => import(/* webpackChunkName: "user-feedback" */ "features/user/feedback/FeedbackPage.js")),
  UserHelpPage: lazy(() => import(/* webpackChunkName: "user-help" */ "features/user/help/HelpPage.js")),
  UserMassclickDocumentsPage: lazy(() => import(/* webpackChunkName: "user-documents" */ "features/user/documents/MassclickDocumentsPage.js")),
  UserMassclickFeedPage: lazy(() => import(/* webpackChunkName: "user-feed" */ "features/user/feed/MassclickFeedPage.js")),
  SpotlightWorkspacePage: lazy(() => import(/* webpackChunkName: "spotlight-workspace" */ "features/user/spotlight-workspace/SpotlightWorkspacePage.js")),
  SpotlightCreatePage: lazy(() => import(/* webpackChunkName: "spotlight-create" */ "features/user/spotlight-create/SpotlightCreatePage.js")),
  UserRewardsPage: lazy(() => import(/* webpackChunkName: "user-rewards" */ "features/user/rewards/RewardsPage.js")),
};

export const AppShellSurfaces = {
  GlobalDrawer: lazy(() => import(/* webpackChunkName: "drawer" */ "features/public/drawer/globalDrawer.js")),
  FloatingButtons: lazy(() => import(/* webpackChunkName: "floating-buttons" */ "features/public/floating/floatingButtons.js")),
  MobileHomeDock: lazy(() => import(/* webpackChunkName: "mobile-home-dock" */ "features/public/mobile-home-dock/MobileHomeDock.js")),
  AppInstallPrompt: lazy(() => import(/* webpackChunkName: "app-install-prompt" */ "features/public/app-install-prompt/AppInstallPrompt.js")),
  OTPLoginModal: lazy(() => import(/* webpackChunkName: "otp-modal" */ "features/public/auth/AddBusinessModal.js")),
  MaintenanceOverlay: lazy(() => import(/* webpackChunkName: "maintenance" */ "shared/components/MaintenanceOverlay.js")),
};

export const FOOTER_ROUTES = [
  { path: "aboutus", Component: FooterPages.AboutUsPage },
  { path: "testimonials", Component: FooterPages.Testimonials },
  { path: "feedbacks", Component: FooterPages.FeedbackComponent },
  { path: "customercare", Component: FooterPages.CustomerCareComponent },
  { path: "portfolio", Component: FooterPages.Portfolio },
  { path: "terms", Component: FooterPages.TermsAndConditions },
  { path: "privacy", Component: FooterPages.PrivacyPolicy },
  { path: "refund", Component: FooterPages.RefundPolicy },
  { path: "enquiry", Component: FooterPages.EnquiryNow },
  { path: "deleteaccount", Component: FooterPages.DeleteAccount },
  { path: "knowledgebase", Component: FooterPages.KnowledgeBasePage },
  { path: "careers", Component: FooterPages.CareersPage },
  { path: "web", Component: FooterPages.WebDevSection },
  { path: "digital", Component: FooterPages.DigitalMarketing },
  { path: "graphic", Component: FooterPages.GraphicDesign },
  { path: "seo", Component: FooterPages.Seo },
];

