import React, { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Home, PlusCircle, LayoutGrid, Newspaper, Image, Crown, Settings, SlidersHorizontal, CheckCircle2, Clock3, ListChecks, CircleDot, Plus, Bell, Flag, Folder, MoreVertical, Trash2, Edit3, Mail, Smartphone, CalendarClock, ChevronLeft, ChevronRight, X } from "lucide-react";
import styles from "./PlannerDashboard.module.css";

const navigation=[[Home,"Spotlight Feed","/user_feed"],[PlusCircle,"Create Post","/user_spotlight/create"],[LayoutGrid,"Planner Overview","/user_spotlight/calendar"],[Newspaper,"My Posts","/user_spotlight/posts"],[Image,"Media Library","/user_spotlight/media"],[Settings,"Settings","/user_spotlight/settings"]];
const seed=[{id:1,title:"Create promotional post for weekend offer",category:"Content",priority:"High",due:"24 Aug 2026, 10:00 AM",status:"In Progress",description:"Create and schedule promotional post for weekend special offer on all services."},{id:2,title:"Review campaign performance",category:"Campaign",priority:"Medium",due:"24 Aug 2026, 12:00 PM",status:"Pending"},{id:3,title:"Update product catalog",category:"Product",priority:"Medium",due:"24 Aug 2026, 2:30 PM",status:"Pending"},{id:4,title:"Respond to customer enquiries",category:"Support",priority:"High",due:"24 Aug 2026, 4:00 PM",status:"Pending"},{id:5,title:"Monthly performance report",category:"Report",priority:"Low",due:"25 Aug 2026, 11:00 AM",status:"Pending"},{id:6,title:"Plan new festival campaign",category:"Campaign",priority:"High",due:"25 Aug 2026, 3:00 PM",status:"Pending"}];
const tabs=["All Tasks","My Tasks","Completed","Overdue"];
const Toggle=({value,onChange,label})=><button type="button" aria-label={label} aria-pressed={value} onClick={()=>onChange(!value)} className={`${styles.toggle} ${value?styles.on:""}`}><i/></button>;

export default function PlannerDashboard({posts=[]}){
 const navigate=useNavigate();
 const [tasks,setTasks]=useState(seed),[selected,setSelected]=useState(seed[0]),[tab,setTab]=useState("All Tasks"),[filters,setFilters]=useState(false),[repeat,setRepeat]=useState(true),[notices,setNotices]=useState({inApp:true,email:true,push:true});
 const [plannerMode,setPlannerMode]=useState("Content Planner"),[calendarView,setCalendarView]=useState("Week"),[week,setWeek]=useState(0);
 const [modal,setModal]=useState(null);
 const [form,setForm]=useState({title:"",description:"",category:"",priority:"",date:"",time:"",reminder:"15 Minutes Before",assignee:""});
 const shown=useMemo(()=>tab==="Completed"?tasks.filter(x=>x.status==="Completed"):tab==="Overdue"?tasks.filter(x=>x.status==="Overdue"):tasks,[tab,tasks]);
 const update=(k,v)=>setForm(old=>({...old,[k]:v}));
 const createTask=()=>{if(!form.title.trim())return;const task={id:Date.now(),title:form.title,description:form.description,category:form.category||"General",priority:form.priority||"Medium",due:[form.date,form.time].filter(Boolean).join(", ")||"Not scheduled",status:"Pending"};setTasks(old=>[task,...old]);setSelected(task);setForm({title:"",description:"",category:"",priority:"",date:"",time:"",reminder:"15 Minutes Before",assignee:""})};
 const markComplete=id=>{setTasks(old=>old.map(x=>x.id===id?{...x,status:"Completed"}:x));setSelected(old=>old?.id===id?{...old,status:"Completed"}:old)}; const removeTask=id=>{setTasks(old=>old.filter(x=>x.id!==id));setSelected(null)};
 const counts={complete:tasks.filter(x=>x.status==="Completed").length,inProgress:tasks.filter(x=>x.status==="In Progress").length,pending:tasks.filter(x=>x.status==="Pending").length};
 const stats=[[ListChecks,tasks.length,"Total Tasks","20% this week","blue"],[CheckCircle2,counts.complete||5,"Completed","15% this week","green"],[CircleDot,counts.inProgress||4,"In Progress","10% this week","violet"],[Clock3,counts.pending,"Pending","5% this week","orange"],[CheckCircle2,"85%","Completion Rate","15% this week","green"]];
 const openDetail=(title,kind,rows,description,action,items)=>setModal({title,kind,rows,description,action,items});
 const tasksForMetric=label=>label==="Completed"?tasks.filter(x=>x.status==="Completed"):label==="In Progress"?tasks.filter(x=>x.status==="In Progress"):label==="Pending"?tasks.filter(x=>x.status==="Pending"):tasks;
 useEffect(()=>{if(!modal)return;const close=e=>e.key==="Escape"&&setModal(null);document.addEventListener("keydown",close);const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",close);document.body.style.overflow=old}},[modal]);
 return <main className={styles.page}><aside className={styles.sidebar}><nav>{navigation.map(([Icon,label,to])=><Link key={label} to={to} className={label==="Planner"?styles.active:""}><Icon/><span>{label}</span></Link>)}</nav><section><Crown/><h3>Go Premium</h3><p>Unlock advanced tools, analytics and more to grow your business.</p><button>Upgrade Now →</button></section></aside><section className={styles.workspace}>
  <header className={styles.heading}><div><h1>Planner Overview</h1><p>Plan, schedule and organise your content and tasks efficiently.</p></div><button onClick={()=>navigate("/user_spotlight/create")}><Plus/>Create Post</button></header>
  <section className={styles.stats}>{stats.map(([Icon,value,label,change,tone])=><article role="button" tabIndex="0" onClick={()=>openDetail(label,"Performance overview",[["Current value",value],["Change",change],["Period","This week"]],`Complete task-level information behind ${label.toLowerCase()}.`,null,tasksForMetric(label))} onKeyDown={e=>e.key==="Enter"&&e.currentTarget.click()} key={label}><i className={styles[tone]}><Icon/></i><div><strong>{value}</strong><span>{label}</span><small>↑ {change}</small></div></article>)}</section>
  <section className={styles.contentPlanner}><nav>{["Content Planner","Task Planner","Campaign Planner","Event Planner"].map(x=><button className={plannerMode===x?styles.selected:""} onClick={()=>setPlannerMode(x)} key={x}>{x}</button>)}</nav><header><div><h2>Calendar View</h2><button onClick={()=>setWeek(v=>v-1)}><ChevronLeft/></button><button onClick={()=>setWeek(v=>v+1)}><ChevronRight/></button><button onClick={()=>setWeek(0)}>Today</button></div><strong>{new Date(2026,7,1+week*7).toLocaleDateString(undefined,{month:"long",year:"numeric"})}</strong><div>{["Day","Week","Month"].map(x=><button className={calendarView===x?styles.selected:""} onClick={()=>setCalendarView(x)} key={x}>{x}</button>)}<button onClick={()=>openDetail("Calendar Filters","Planner controls",[["Current planner",plannerMode],["Calendar view",calendarView],["Visible posts",Math.min(posts.length||7,7)]],"Use planner and view filters to focus the schedule on the work that matters now.")}><SlidersHorizontal/>Filters</button></div></header><div className={styles.calendarViewport}><div className={styles.calendarDays}><span/>{[17,18,19,20,21,22,23].map((d,i)=><button onClick={()=>openDetail(`${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][i]}, ${d} August`,"Calendar day",[["Scheduled items",i===2?2:1],["Available hours","9 AM – 5 PM"]],"Review everything scheduled for this day.")} className={i===2?styles.current:""} key={d}><b>{d}</b><small>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][i]}</small></button>)}</div><div className={styles.calendarSchedule}><aside>{["9 AM","10 AM","11 AM","12 PM","1 PM","2 PM","3 PM","4 PM","5 PM"].map(x=><span key={x}>{x}</span>)}</aside><div className={styles.calendarLines}>{Array.from({length:63},(_,i)=><i key={i}/>)}</div>{(posts.length?posts.slice(0,7).map((p,i)=>[p.title||p.businessName||"Spotlight Post",`${9+i%7}:00 ${i>3?"PM":"AM"}`,i,p]):[["Product Post","9:00 AM",1],["Offer Update","10:30 AM",2],["Event Promo","9:30 AM",3],["Campaign Post","11:00 AM",5],["Service Highlight","1:00 PM",0],["Video Post","2:00 PM",2],["Announcement","3:00 PM",4]]).map(([name,time,day,post],i)=><button onClick={()=>openDetail(name,post?.postType||"Scheduled content",[["Time",time],["Day",["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][day]],["Status",post?.status||"Scheduled"],["Audience",post?.audience?.join?.(", ")||"Local customers"]],post?.text||"This item is scheduled in your Spotlight content planner.",post?()=>navigate(`/user_feed?post=${post._id}`):null)} style={{"--day":day,"--row":i%7+1}} className={`${styles.calendarEvent} ${styles[`event${i%7}`]}`} key={`${name}-${i}`}><strong>{name}</strong><small>{time}</small><b>⋮</b></button>)}</div></div></section>
  <div className={styles.taskLayout}><section className={styles.taskTableCard}><header className={styles.taskTabs}>{tabs.map(x=><button className={tab===x?styles.selected:""} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button className={filters?styles.filterOn:""} onClick={()=>setFilters(v=>!v)}><SlidersHorizontal/>Filters</button></header>{filters&&<div className={styles.taskFilters}>{["All Categories","All Priorities","All Statuses"].map(x=><select key={x}><option>{x}</option></select>)}</div>}<div className={styles.tableScroll}><table><thead><tr><th>Task</th><th>Category</th><th>Priority</th><th>Due Date</th><th>Status</th><th/></tr></thead><tbody>{shown.map(task=><tr className={selected?.id===task.id?styles.rowSelected:""} key={task.id} onClick={()=>setSelected(task)}><td><input type="checkbox" checked={task.status==="Completed"} onChange={()=>markComplete(task.id)}/><strong>{task.title}</strong></td><td>{task.category}</td><td><em className={styles[task.priority.toLowerCase()]}>{task.priority}</em></td><td>{task.due}</td><td><span className={styles[task.status.toLowerCase().replace(" ","")]}>{task.status}</span></td><td><MoreVertical/></td></tr>)}</tbody></table></div><footer>Showing 1 to {shown.length} of {tasks.length} tasks <span><button>1</button><button>2</button><button>›</button></span></footer></section>
   <aside className={styles.taskRight}><section className={styles.todayTasks}><header><h2>Today&apos;s Tasks</h2><button>View All</button></header>{tasks.slice(0,4).map(task=><label key={task.id}><input type="checkbox" checked={task.status==="Completed"} onChange={()=>markComplete(task.id)}/><span>{task.title}</span><em className={styles[task.priority.toLowerCase()]}>{task.priority}</em><small>{task.due.split(", ")[1]}</small></label>)}<button className={styles.addTask} onClick={()=>document.getElementById("task-form")?.scrollIntoView({behavior:"smooth"})}><Plus/>Add New Task</button></section><section className={styles.upcomingTasks}><header><h2>Upcoming Posts</h2><button onClick={()=>navigate("/user_feed")}>View All</button></header>{(posts.length?posts.slice(0,4):tasks.slice(0,4)).map((item,i)=><button key={item._id||item.id} onClick={()=>item._id&&navigate(`/user_feed?post=${item._id}`)}><time><b>{22+i}</b>AUG</time><span><strong>{item.title||item.businessName}</strong><small>{item.postType||item.category}</small></span></button>)}</section><section className={styles.completion}><header><h2>Task Completion</h2><small>Last 7 Days⌄</small></header><div><figure><div>85%</div><figcaption>Completed</figcaption></figure><span><strong>{Math.max(counts.complete,12)}</strong><small>Completed</small></span><span><strong>{Math.max(tasks.length,15)}</strong><small>Total Tasks</small></span></div></section></aside></div>
  <div className={styles.detailGrid}><section className={styles.taskForm} id="task-form"><header><h2>Add New Task</h2><button>×</button></header><label>Task Title *<input value={form.title} onChange={e=>update("title",e.target.value)} placeholder="Enter task title"/></label><label>Description<textarea value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Add task description..."/></label><div><label>Category<select value={form.category} onChange={e=>update("category",e.target.value)}><option value="">Select category</option><option>Content</option><option>Campaign</option><option>Product</option><option>Support</option></select></label><label>Priority<select value={form.priority} onChange={e=>update("priority",e.target.value)}><option value="">Select priority</option><option>High</option><option>Medium</option><option>Low</option></select></label><label>Due Date<input type="date" value={form.date} onChange={e=>update("date",e.target.value)}/></label><label>Due Time<input type="time" value={form.time} onChange={e=>update("time",e.target.value)}/></label></div><label>Reminder<select value={form.reminder} onChange={e=>update("reminder",e.target.value)}><option>15 Minutes Before</option><option>1 Hour Before</option><option>1 Day Before</option></select></label><label>Assign To<select value={form.assignee} onChange={e=>update("assignee",e.target.value)}><option value="">Select assignee (optional)</option><option>Prem</option><option>Marketing Team</option></select></label><footer><button onClick={()=>update("title","")}>Cancel</button><button onClick={createTask}>Create Task</button></footer></section>
   <section className={styles.taskDetail}><header><h2>Task Details</h2><span><button><Edit3/>Edit</button><MoreVertical/></span></header>{selected?<><div className={styles.detailTitle}><h3>{selected.title}</h3><em className={styles[selected.priority.toLowerCase()]}>{selected.priority} Priority</em></div><small>{selected.category}　•　Created by Prem　•　23 Aug 2026, 9:15 AM</small><p>{selected.description||"Complete this task on time and keep your business workflow moving."}</p><dl>{[["Due Date",selected.due.split(", ")[0]],["Due Time",selected.due.split(", ")[1]||"Not set"],["Reminder","15 Minutes Before"],["Status",selected.status],["Assign To","Prem"]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><footer><button onClick={()=>markComplete(selected.id)}><CheckCircle2/>Mark as Completed</button><button onClick={()=>removeTask(selected.id)}><Trash2/>Delete Task</button></footer></>:<p>Select a task to view its details.</p>}</section>
   <aside className={styles.settingsGrid}><section><h2>Task Status</h2><p>Track your task progress</p>{[[Clock3,"Pending","Not started yet","orange"],[CircleDot,"In Progress","Currently working on it","blue"],[CheckCircle2,"Completed","Task completed","green"]].map(([Icon,a,b,t])=><div key={a}><i className={styles[t]}><Icon/></i><span><strong>{a}</strong><small>{b}</small></span></div>)}</section><section><h2>Priority Levels</h2><p>Set priority to focus better</p>{[["High","Important & urgent"],["Medium","Important but not urgent"],["Low","Not urgent"]].map(([a,b])=><div key={a}><i><Flag/></i><span><strong>{a}</strong><small>{b}</small></span></div>)}</section><section><header><h2>Recurring Tasks</h2><Toggle value={repeat} onChange={setRepeat} label="Recurring tasks"/></header><p>Automate your repeating tasks</p><label>Repeat<select><option>Every Week</option><option>Every Month</option></select></label><div className={styles.weekdays}>{["Mon","Tue","Wed","Thu","Fri"].map(x=><button key={x}>{x}</button>)}</div></section><section><header><h2>Smart Notifications</h2><Toggle value={notices.inApp||notices.email||notices.push} onChange={v=>setNotices({inApp:v,email:v,push:v})} label="All notifications"/></header><p>Get notified on time</p>{[[Bell,"inApp","In-App Notification"],[Mail,"email","Email Reminder"],[Smartphone,"push","Push Notification"]].map(([Icon,key,label])=><div key={key}><Icon/><span><strong>{label}</strong><small>Reliable reminders</small></span><Toggle value={notices[key]} onChange={v=>setNotices(old=>({...old,[key]:v}))} label={label}/></div>)}</section></aside></div>
  <section className={styles.workflow}><h2>Planner Workflow — Step by Step</h2><div>{[[PlusCircle,"Add Task","Fill in the details"],[Folder,"Organize","Set category and priority"],[CalendarClock,"Schedule","Set due date and reminder"],[ListChecks,"Track","Monitor dashboard progress"],[Bell,"Get Notified","Receive timely updates"],[CheckCircle2,"Complete","Achieve your goals"]].map(([Icon,a,b],i)=><React.Fragment key={a}><article><b>{i+1}</b><Icon/><strong>{a}</strong><small>{b}</small></article>{i<5&&<span>→</span>}</React.Fragment>)}</div></section>
 </section>{modal&&<div className={styles.modalBackdrop} role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className={`${styles.detailModal} ${modal.items?styles.recordsModal:""}`} role="dialog" aria-modal="true" aria-labelledby="planner-modal-title"><header><div><small>{modal.kind}</small><h2 id="planner-modal-title">{modal.title}</h2></div><button autoFocus onClick={()=>setModal(null)} aria-label="Close details"><X/></button></header><div className={styles.modalBody}><p>{modal.description}</p><dl>{modal.rows?.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{String(value??"Not available")}</dd></div>)}</dl>{modal.items&&<section className={styles.modalRecords}><header><h3>Task Details</h3><span>{modal.items.length} record{modal.items.length===1?"":"s"}</span></header>{modal.items.length?modal.items.map((task,index)=><article key={task.id}><b>{index+1}</b><div><strong>{task.title}</strong><small>{task.category} · Due {task.due}</small></div><em className={styles[task.priority.toLowerCase()]}>{task.priority}</em><span className={styles[task.status.toLowerCase().replace(" ","")]}>{task.status}</span><button onClick={()=>{setSelected(task);setModal(null);document.getElementById("task-form")?.scrollIntoView({behavior:"smooth"})}}>Open</button></article>):<div className={styles.noRecords}>No tasks currently match this status.</div>}</section>}</div><footer><button onClick={()=>setModal(null)}>Close</button>{modal.action&&<button onClick={()=>{setModal(null);modal.action()}}>View Full Details</button>}</footer></section></div>}</main>;
}
