import React, { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Link, useNavigate } from "react-router-dom";
import { Home, PlusCircle, LayoutGrid, Newspaper, Images, Settings, Search, MoreVertical, Eye, Upload, UserRound, Bell, ShieldCheck, CreditCard, Plug, LockKeyhole } from "lucide-react";
import StickySearchBar from "../../StickySearchBar/StickySearchBar";
import { getMassclickFeedPosts } from "../../../../redux/actions/massclickFeedAction.js";
import styles from "./SpotlightWorkspacePage.module.css";
import PlannerDashboard from "./PlannerDashboard";

const workspaceNav=[[Home,"Spotlight Feed","/user_feed"],[PlusCircle,"Create Post","/user_spotlight/create"],[LayoutGrid,"Planner Overview","/user_spotlight/calendar"],[Newspaper,"My Posts","/user_spotlight/posts"],[Images,"Media Library","/user_spotlight/media"],[Settings,"Settings","/user_spotlight/settings"]];
const getUser=()=>{try{return JSON.parse(localStorage.getItem("authUser")||"{}")||{}}catch{return {}}};
const idOf=value=>String(value?._id||value?.id||value||"");
const format=n=>Number(n||0).toLocaleString();
const Empty=({children})=><div className={styles.empty}>{children}</div>;
function Shell({active,children}){return <><StickySearchBar/><main className={styles.page}><aside className={styles.workspaceSidebar}><nav>{workspaceNav.map(([Icon,label,to])=><Link className={label===active?styles.sidebarActive:""} to={to} key={label}><Icon/><span>{label}</span></Link>)}</nav></aside><section className={styles.workspace}>{children}</section></main></>}

function MyPosts({posts,loading,error}){
 const navigate=useNavigate(),[tab,setTab]=useState("All Posts"),[query,setQuery]=useState("");
 const user=getUser(),uid=idOf(user.userId||user._id||user.id),owned=posts.filter(post=>post.isOwner||Boolean(uid&&idOf(post.ownerUserId)===uid));
 const shown=owned.filter(post=>(tab==="All Posts"||String(post.status||"active").toLowerCase()===tab.toLowerCase())&&`${post.title||""} ${post.text||""}`.toLowerCase().includes(query.toLowerCase()));
 return <Shell active="My Posts"><header className={styles.managerHead}><div><h1>My Posts</h1><p>Manage, edit and track all your Spotlight posts.</p></div><Link className={styles.primary} to="/user_spotlight/create">+ Create Post</Link></header><section className={styles.managerCard}><nav className={styles.managerTabs}>{["All Posts","Active","Scheduled","Draft","Expired"].map(x=><button className={tab===x?styles.selected:""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className={styles.managerFilters}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search posts..."/></label><select><option>All Types</option></select><select><option>This Month</option></select></div><div className={styles.managerTable}><table><thead><tr><th>Post</th><th>Type</th><th>Status</th><th>Views</th><th>Engagement</th><th>Date</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="7"><Empty>Loading posts…</Empty></td></tr>:error?<tr><td colSpan="7"><Empty>Unable to load posts.</Empty></td></tr>:!shown.length?<tr><td colSpan="7"><Empty>No posts available.</Empty></td></tr>:shown.map(post=>{const engagement=(post.likesCount??post.likes?.length??0)+(post.commentsCount??post.comments?.length??0)+(post.sharesCount??0);return <tr key={post._id}><td><div className={styles.postThumb}>{post.mediaItems?.[0]?.mediaUrl?<img src={post.mediaItems[0].mediaUrl} alt=""/>:<Newspaper/>}</div><span><strong>{post.title||post.text||"Untitled post"}</strong><small>{post.businessName||"Spotlight"}</small></span></td><td><em>{post.postType||"Update"}</em></td><td><b className={styles.status}>{post.status||"active"}</b></td><td>{format(post.viewsCount)}</td><td>{format(engagement)}</td><td>{post.createdAt?new Date(post.createdAt).toLocaleDateString():"—"}</td><td><button onClick={()=>navigate(`/user_feed?post=${post._id}`)} aria-label="Open post"><Eye/></button><button aria-label="More actions"><MoreVertical/></button></td></tr>})}</tbody></table></div><footer>Showing {shown.length} of {owned.length} posts</footer></section></Shell>
}

function MediaLibrary({posts,loading,error}){
 const navigate=useNavigate(),[tab,setTab]=useState("All Files"),[query,setQuery]=useState("");
 const user=getUser(),uid=idOf(user.userId||user._id||user.id);
 const media=useMemo(()=>posts.filter(post=>post.isOwner||Boolean(uid&&idOf(post.ownerUserId)===uid)).flatMap(post=>(post.mediaItems||[]).map((item,index)=>({...item,post,index}))),[posts,uid]);
 const shown=media.filter(item=>(tab==="All Files"||tab==="Images"&&item.mediaType==="image"||tab==="Videos"&&item.mediaType==="video"||tab==="Documents"&&!['image','video'].includes(item.mediaType))&&`${item.fileName||""} ${item.post.title||""}`.toLowerCase().includes(query.toLowerCase()));
 return <Shell active="Media Library"><header className={styles.managerHead}><div><h1>Media Library</h1><p>Search and manage all images, videos and documents from your posts.</p></div><button className={styles.primary} onClick={()=>navigate("/user_spotlight/create")}><Upload/> Upload New</button></header><section className={styles.managerCard}><nav className={styles.managerTabs}>{["All Files","Images","Videos","Documents"].map(x=><button className={tab===x?styles.selected:""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className={styles.managerFilters}><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search media..."/></label><select><option>All Types</option></select></div>{loading?<Empty>Loading media…</Empty>:error?<Empty>Unable to load media.</Empty>:!shown.length?<Empty>No media files available.</Empty>:<section className={styles.libraryGrid}>{shown.map((item,i)=><article key={`${item.mediaKey||item.fileName}-${i}`} onClick={()=>navigate(`/user_feed?post=${item.post._id}`)}>{item.mediaType==="video"?<video src={item.mediaUrl} controls onClick={e=>e.stopPropagation()}/>:item.mediaType==="image"?<img src={item.mediaUrl} alt={item.fileName||item.post.title||"Post media"}/>:<div className={styles.document}><Images/><b>{item.fileName?.split(".").pop()?.toUpperCase()||"FILE"}</b></div>}<footer><strong>{item.fileName||item.post.title||"Media file"}</strong><small>{item.post.title||item.post.businessName}</small></footer></article>)}</section>}<footer>Showing {shown.length} of {media.length} files</footer></section></Shell>
}

function SpotlightSettings(){
 const navigate=useNavigate(),user=getUser(),[section,setSection]=useState("Profile Settings"),[notice,setNotice]=useState(()=>localStorage.getItem("spotlightNotifications")!=="off");
 const sections=[[UserRound,"Profile Settings"],[Newspaper,"Business Profile"],[Bell,"Notifications"],[ShieldCheck,"Account & Security"],[LockKeyhole,"Roles & Permissions"],[CreditCard,"Billing & Subscription"],[Plug,"Integrations"]];
 return <Shell active="Settings"><header className={styles.managerHead}><div><h1>Settings</h1><p>Manage your account, preferences and integrations.</p></div></header><section className={styles.settingsCard}><aside>{sections.map(([Icon,label])=><button className={section===label?styles.settingActive:""} onClick={()=>setSection(label)} key={label}><Icon/>{label}</button>)}</aside><div className={styles.settingsForm}><h2>{section}</h2>{section==="Profile Settings"?<><div className={styles.profileRow}><span>{(user.userName||user.name||user.businessName||"U").charAt(0)}</span><div><strong>{user.userName||user.name||user.businessName||"User"}</strong><small>MassClick profile</small></div><button onClick={()=>navigate("/user_edit-profile")}>Change Photo</button></div><label>Full Name<input readOnly value={user.userName||user.name||""}/></label><label>Email Address<input readOnly value={user.email||user.emailAddress||""}/></label><label>Phone Number<input readOnly value={user.phoneNumber||user.mobileNumber||user.contact||""}/></label><label>Language<select defaultValue="English"><option>English</option></select></label><label>Time Zone<select defaultValue="Asia/Kolkata"><option value="Asia/Kolkata">GMT +05:30 India Standard Time</option></select></label><footer><button onClick={()=>navigate("/user_edit-profile")}>Edit Profile</button></footer></>:section==="Notifications"?<><div className={styles.preference}><span><strong>Spotlight notifications</strong><small>Receive updates about posts and activity.</small></span><button className={notice?styles.toggleOn:""} onClick={()=>setNotice(v=>!v)}><i/></button></div><footer><button onClick={()=>localStorage.setItem("spotlightNotifications",notice?"on":"off")}>Save Preference</button></footer></>:<Empty>{section} is managed from your main MassClick account settings.</Empty>}</div></section></Shell>
}

export default function SpotlightWorkspacePage({mode}){
 const dispatch=useDispatch(),{posts=[],loading,error}=useSelector(state=>state.massclickFeed||{});
 useEffect(()=>{if(mode!=="settings")dispatch(getMassclickFeedPosts({pageSize:50})).catch(()=>{})},[dispatch,mode]);
 if(mode==="calendar")return <><StickySearchBar/><PlannerDashboard posts={posts} loading={loading}/></>;
 if(mode==="posts")return <MyPosts posts={posts} loading={loading} error={error}/>;
 if(mode==="settings")return <SpotlightSettings/>;
 return <MediaLibrary posts={posts} loading={loading} error={error}/>;
}
