export const PAGE_REGISTRY = [
  { path: '/dashboard/analytics-overview', label: 'Analytics Overview' },
  { path: '/dashboard/site-analytics', label: 'Site Analytics' },
  { path: '/dashboard/data-analytics', label: 'Category Coverage' },
  { path: '/dashboard/ga4-analytics', label: 'Google Analytics 4' },
  { path: '/dashboard/gsc-analytics', label: 'Google Search Console' },
  { path: '/dashboard/msg91-analytics', label: 'MSG91 Analytics' },
  { path: '/dashboard/gmaps-leads', label: 'Google Maps Leads' },
  { path: '/dashboard/clients',             label: 'Clients' },
  { path: '/dashboard/business',            label: 'Business' },
  { path: '/dashboard/category',            label: 'Category' },
  { path: '/dashboard/location',            label: 'Location' },
  { path: '/dashboard/master-location',     label: 'Master Locations' },
  { path: '/dashboard/seo',                 label: 'SEO Management' },
  { path: '/dashboard/seopagecontent',      label: 'SEO Page Content' },
  { path: '/dashboard/seopagecontentblogs', label: 'SEO Blogs' },
  { path: '/dashboard/seotemplates',        label: 'SEO Templates' },
  { path: '/dashboard/authors',             label: 'Authors' },
  { path: '/dashboard/enquiry',             label: 'Enquiry' },
  { path: '/dashboard/customer-care',       label: 'Care Chat' },
  { path: '/dashboard/advertisements',      label: 'Advertisements' },
  { path: '/dashboard/quotation',           label: 'Quotations' },
  { path: '/dashboard/documents',           label: 'Documents' },
  { path: '/dashboard/feed',                label: 'Feed' },
  { path: '/dashboard/mni-data',            label: 'MNI Data' },
  { path: '/dashboard/terms-conditions-data', label: 'Terms & Conditions' },
  { path: '/dashboard/fcm-marketing',       label: 'Push Notify' },
  { path: '/dashboard/event-location',      label: 'EventLocation' },
  { path: '/dashboard/massclick-events',    label: 'MassclickEvents' },
  { path: '/dashboard/event-category',      label: 'EventCategory' },
  { path: '/dashboard/event-creation',      label: 'EventCreation' },
  { path: '/dashboard/event-advertisement', label: 'EventAdvertisement' },
  { path: '/dashboard/user',                label: 'Users' },
  { path: '/dashboard/roles',               label: 'Roles' },
  { path: '/dashboard/category-display',    label: 'Display' },
  { path: '/dashboard/public-users-count',  label: 'Public Count' },
  { path: '/dashboard/auth-console',        label: 'Auth Console' },
  { path: '/dashboard/system-settings',     label: 'System Settings' },
];
