const POLICY_LIST = [
  {
    key: "favorites.add",
    method: "POST",
    path: "/api/favorites/add",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "favorites.remove",
    method: "POST",
    path: "/api/favorites/remove",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "favorites.list",
    method: "GET",
    path: "/api/favorites/list",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "favorites.check",
    method: "GET",
    path: "/api/favorites/check",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "otp.profile.view",
    method: "GET",
    path: "/api/otp_user/:mobile",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "otp.profile.update",
    method: "PUT",
    path: "/api/otp_user_update/:mobile",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "otp.profile.search-history",
    method: "POST",
    path: "/api/otp_user/log-search",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "otp.profile.list",
    method: "GET",
    path: "/api/otp_users",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "otp.profile.delete",
    method: "DELETE",
    path: "/api/otp_user/:mobile",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "fcm.web-register",
    method: "POST",
    path: "/api/fcm-token/web-register",
    allowedActorTypes: ["customer"],
    ownership: "self-only",
  },
  {
    key: "fcm.save",
    method: "POST",
    path: "/api/fcm-token/save",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "fcm.refresh",
    method: "PUT",
    path: "/api/fcm-token/refresh/:userId/:oldToken",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "fcm.remove",
    method: "DELETE",
    path: "/api/fcm-token/remove/:userId/:token",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "fcm.list",
    method: "GET",
    path: "/api/fcm-token/:userId",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "fcm.send-single",
    method: "POST",
    path: "/api/fcm-token/send-single",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "fcm.send-bulk",
    method: "POST",
    path: "/api/fcm-token/send-bulk",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "chat.customer",
    method: "ALL",
    path: "/api/chat/*",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
  },
  {
    key: "leads.customer.list",
    method: "GET",
    path: "/api/leadsData/leads/:mobileNumber",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "leads.customer.summary",
    method: "GET",
    path: "/api/leadsData/analytics/summary/:mobileNumber",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "leads.customer.trends",
    method: "GET",
    path: "/api/leadsData/analytics/trends/:mobileNumber",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "leads.customer.top-searches",
    method: "GET",
    path: "/api/leadsData/analytics/top-searches/:mobileNumber",
    allowedActorTypes: ["customer", "admin"],
    ownership: "self-only",
    adminOverride: true,
  },
  {
    key: "auth.admin.overview",
    method: "GET",
    path: "/api/admin/auth/overview",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "auth.admin.sessions",
    method: "GET",
    path: "/api/admin/auth/sessions",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "auth.admin.introspect",
    method: "POST",
    path: "/api/admin/auth/introspect",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
  {
    key: "auth.admin.audit",
    method: "GET",
    path: "/api/admin/auth/audit",
    allowedActorTypes: ["admin"],
    ownership: "admin-managed",
  },
];

const POLICY_MAP = new Map(POLICY_LIST.map((policy) => [policy.key, Object.freeze(policy)]));

export const getAuthPolicy = (key) => POLICY_MAP.get(key) || null;
export const listAuthPolicies = () => POLICY_LIST.map((policy) => ({ ...policy }));
