export const categoriesData = {
  contractors: [
    "Civil Contractors",
    "Electrical Contractors",
    "Plumbing Contractors",
    "Painting Contractor",
    "Building Contractors",
    "Flooring Contractors",
    "Carpentry Contractors",
    "Interior Contractors",
    "False Ceiling Contractors",
    "Road Construction Contractors",
    "Labour Contractors",
    "Fabrication Contractors",
    "Borewell Contractors",
    "Drainage Contractors",
    "Pipeline Contractors",
    "Roofing Contractors",
    "Waterproofing Contractors",
    "Tiling Contractors",
    "Welding Contractors",
    "Fire Fighting Contractors",
  ],
};