export const categoriesData = {
  
  contractor: [
    { name: "Civil Contractors" },
    { name: "Electrical Contractors" },
    { name: "Plumbing Contractors" },
    { name: "Painting Contractor" },
    { name: "Building Contractors" },
    { name: "Flooring Contractors" },
    { name: "Carpentry Contractors" },
    { name: "Interior Contractors" },
    { name: "False Ceiling Contractors" },
    { name: "Road Construction Contractors" },
    { name: "Labour Contractors" },
    { name: "Fabrication Contractors" },
    { name: "Borewell Contractors" },
    { name: "Drainage Contractors" },
    { name: "Pipeline Contractors" },
    { name: "Roofing Contractors" },
    { name: "Waterproofing Contractors" },
    { name: "Tiling Contractors" },
    { name: "Welding Contractors" },
    { name: "Fire Fighting Contractors" },
  ],

  education: [
    { name: "Schools" },
    { name: "Colleges" },
    { name: "Tutorials" },
    { name: "Vocational Training" },
    { name: "Special Schools" },
    { name: "Children Schools" },
    { name: "Play Schools" },
    { name: "Kindergartens" },
    { name: "Coaching Centers" },
    { name: "Online Education" },
    { name: "Skill Development Institutes" },
    { name: "Language Training Centers" },
  ],

  "rent-and-hire": [
    { name: "Car Rental" },
    { name: "AC On Rent" },
    { name: "Bridal Wear On Rent" },
    { name: "Cameras On Rent" },
    { name: "Cranes On Rent" },
    { name: "Farm House On Rent" },
    { name: "Mini Trucks On Rent" },
    { name: "Projectors On Rent" },
    { name: "Tempo Travellers On Rent" },

    { name: "Costumes On Rent" },
    { name: "Furnitures On Rent" },
    { name: "Bungalows On Rent" },
    { name: "Chairs On Rent" },
    { name: "DJ Equipments On Rent" },
    { name: "Generators On Rent" },
    { name: "Bike On Rent" },
    { name: "Rooms On Rent" },
    { name: "Trucks On Rent" },

    { name: "Mini Bus On Rent" },
    { name: "Air Coolers On Rent" },
    { name: "Bus On Rent" },
    { name: "Cooks On Rent" },
    { name: "Dead Body Freezer Box On Rent" },
    { name: "Laptops On Rent" },
    { name: "Passenger Van On Rent" },
    { name: "Sound Systems On Rent" },
    { name: "Vans On Rent" },
  ],

  hospitals: [
    { name: "Hospitals" },
    { name: "Eye Hospitals" },
    { name: "Private Hospitals" },
    { name: "Ayurvedic Hospitals" },
    { name: "Dentist" },
    { name: "Kidney Hospitals" },
    { name: "Orthopedic Hospitals" },

    { name: "Children Hospitals" },
    { name: "Maternity Hospitals" },
    { name: "Public Hospitals" },
    { name: "Cancer Hospitals" },
    { name: "Diabetic Centres" },
    { name: "Neurological Hospitals" },
    { name: "Swine Flu Testing Centres" },

    { name: "ENT Hospitals" },
    { name: "Multispeciality Hospitals" },
    { name: "Veterinary Hospitals" },
    { name: "Cardiac Hospitals" },
    { name: "Public Veterinary Hospitals" },
    { name: "Nursing Homes" },
    { name: "Tuberculosis Hospitals" },
  ],

  "packers-and-movers": [
    { name: "Packers And Movers" },
    { name: "Packers And Movers Within City" },
    { name: "Packers And Movers All India" },
    { name: "Packers And Movers Outside India" },
    { name: "Packers And Movers For Automobile" },
    { name: "Packers And Movers For Commercial" },
    { name: "Transporters" },
  ],

};