import fs from "fs";
import path from "path";

import dotenv from "dotenv";
import { MongoClient } from "mongodb";

dotenv.config();

// Applies a reviewed coordinate source dry-run report to masterlocations.
//
// This script writes only when --apply is passed. It updates accepted locality
// candidates and tight parent candidates from a report generated by
// dryRunMasterLocationCoordinateSources.js. Review rejects and insufficient
// rows are never written.
//
// Examples:
//   node utils/applyMasterLocationCoordinateSourceReport.js --report=server/reports/report.json
//   node utils/applyMasterLocationCoordinateSourceReport.js --report=server/reports/report.json --apply

const PROD_DB = "massClick";

const parseArgs = (argv) => {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg.startsWith("--")) {
      out._.push(arg);
      continue;
    }

    const eq = arg.indexOf("=");
    if (eq !== -1) {
      out[arg.slice(2, eq)] = arg.slice(eq + 1);
      continue;
    }

    const key = arg.slice(2);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith("--")) out[key] = true;
    else {
      out[key] = next;
      i++;
    }
  }
  return out;
};

const args = parseArgs(process.argv.slice(2));
const APPLY = Boolean(args.apply);
const INCLUDE_LOW = args["include-low"] !== "false";
const INCLUDE_PARENTS = args["include-parents"] !== "false";
const REPORT_FILE = args.report ? path.resolve(args.report) : "";

const usage = () => {
  console.log(`
Usage:
  node utils/applyMasterLocationCoordinateSourceReport.js --report=<path> [options]

Options:
  --apply                       Write changes. Without this, prints a dry-run summary.
  --uri=<mongodb-uri>           Overrides MONGO_URL/MC_URI.
  --db=<name>                   Overrides the database name in the URI path.
  --prod                        Required if --db=massClick or URI points at massClick.
  --include-low=false           Skip lowSingleBusiness locality candidates.
  --include-parents=false       Skip parent ward/zone/district candidates.
`);
};

if (args.help || !REPORT_FILE) {
  usage();
  process.exit(args.help ? 0 : 2);
}

const getMongoUri = () => {
  const uri = args.uri || process.env.MC_URI || process.env.MONGO_URL;
  if (!uri) throw new Error("Mongo URI missing. Set MONGO_URL/MC_URI or pass --uri.");

  const url = new URL(uri);
  if (args.db) url.pathname = `/${args.db}`;
  const dbName = url.pathname.replace(/^\//, "") || args.db || "";
  if (dbName === PROD_DB && !args.prod) {
    throw new Error("Refusing to touch production massClick without --prod.");
  }
  return { uri: url.toString(), dbName };
};

const sourceForTier = (tier) => {
  if (tier === "highBoth") return "mixed-derived";
  if (tier === "businessOnly" || tier === "lowSingleBusiness") return "business-derived";
  if (tier === "gmapsOnly") return "gmaps-leads-derived";
  return "";
};

const confidenceForCandidate = (candidate) => {
  if (candidate.tier === "highBoth") return "high";
  if (candidate.tier === "lowSingleBusiness") return "low";
  if (candidate.selected?.p80Km <= 2 && (candidate.sourceCounts?.business || candidate.sourceCounts?.gmaps || 0) >= 5) {
    return "high";
  }
  return "medium";
};

const parentQuery = (candidate) => {
  if (candidate.level === "district") {
    return { level: "district", district: candidate.district, isActive: { $ne: false } };
  }
  if (candidate.level === "zone") {
    return {
      level: "zone",
      district: candidate.district,
      zone: candidate.zone,
      isActive: { $ne: false },
    };
  }
  if (candidate.level === "ward") {
    return {
      level: "ward",
      district: candidate.district,
      zone: candidate.zone,
      ward: candidate.ward,
      isActive: { $ne: false },
    };
  }
  throw new Error(`Unsupported parent level: ${candidate.level}`);
};

// Both update builders below $set the whole coordinatesMeta object, so a
// locked document reaching updateOne would lose its lock along with its
// hand-placed coordinate. Check before writing, not after.
// See coordinatesMeta.lockedAt in schema/location/masterLocationSchema.js.
const LOCK_PROJECTION = { projection: { _id: 1, "coordinatesMeta.lockedAt": 1 } };
const isLocked = (doc) => Boolean(doc?.coordinatesMeta?.lockedAt);

const buildLocalityUpdate = (candidate, now) => ({
  $set: {
    coordinates: {
      type: "Point",
      coordinates: candidate.selected.coordinates,
    },
    coordinatesMeta: {
      source: sourceForTier(candidate.tier),
      confidence: confidenceForCandidate(candidate),
      query: [
        candidate.district,
        candidate.zone,
        candidate.ward,
        candidate.locality,
        candidate.pincode,
      ].filter(Boolean).join(", "),
      formattedAddress: `dry-run coordinate source: ${candidate.reason}`,
      placeId: "",
      derivedFromCount: (candidate.sourceCounts?.business || 0) + (candidate.sourceCounts?.gmaps || 0),
      updatedAt: now,
    },
    updatedAt: now,
  },
});

const buildParentUpdate = (candidate, now) => ({
  $set: {
    coordinates: {
      type: "Point",
      coordinates: candidate.center,
    },
    coordinatesMeta: {
      source: "derived-from-children",
      confidence: candidate.p80Km <= 5 ? "high" : "medium",
      query: [
        candidate.district,
        candidate.zone,
        candidate.ward,
        candidate.level,
      ].filter(Boolean).join(", "),
      formattedAddress: "derived from accepted child locality coordinates",
      placeId: "",
      derivedFromCount: candidate.childCoordinateCount,
      updatedAt: now,
    },
    updatedAt: now,
  },
});

const main = async () => {
  const report = JSON.parse(fs.readFileSync(REPORT_FILE, "utf8"));
  const candidates = (report.candidates || []).filter((candidate) => {
    if (!candidate.selected?.coordinates) return false;
    if (!INCLUDE_LOW && candidate.tier === "lowSingleBusiness") return false;
    return ["highBoth", "businessOnly", "gmapsOnly", "lowSingleBusiness"].includes(candidate.tier);
  });
  const parentCandidates = INCLUDE_PARENTS ? report.parentCandidates || [] : [];

  const { uri, dbName } = getMongoUri();
  const client = new MongoClient(uri, { serverSelectionTimeoutMS: 5000 });
  await client.connect();

  const db = client.db(dbName);
  const masterlocations = db.collection("masterlocations");
  const now = new Date();

  const summary = {
    database: dbName,
    report: REPORT_FILE,
    apply: APPLY,
    includeLow: INCLUDE_LOW,
    includeParents: INCLUDE_PARENTS,
    localityCandidates: candidates.length,
    parentCandidates: parentCandidates.length,
    localityMatched: 0,
    localityWouldUpdate: 0,
    localityUpdated: 0,
    localitySkippedNoMatch: 0,
    localitySkippedDuplicateMatch: 0,
    localitySkippedLocked: 0,
    parentMatched: 0,
    parentWouldUpdate: 0,
    parentUpdated: 0,
    parentSkippedNoMatch: 0,
    parentSkippedDuplicateMatch: 0,
    parentSkippedLocked: 0,
    byTier: {},
  };

  const problems = [];

  for (const candidate of candidates) {
    summary.byTier[candidate.tier] = (summary.byTier[candidate.tier] || 0) + 1;
    const query = { slug: candidate.slug, level: "locality", isActive: { $ne: false } };
    const matches = await masterlocations.find(query, LOCK_PROJECTION).toArray();
    if (matches.length === 0) {
      summary.localitySkippedNoMatch++;
      problems.push({ type: "locality-no-match", slug: candidate.slug });
      continue;
    }
    if (matches.length > 1) {
      summary.localitySkippedDuplicateMatch++;
      problems.push({ type: "locality-duplicate-match", slug: candidate.slug, matches: matches.length });
      continue;
    }
    if (isLocked(matches[0])) {
      summary.localitySkippedLocked++;
      continue;
    }

    summary.localityMatched++;
    summary.localityWouldUpdate++;
    if (APPLY) {
      await masterlocations.updateOne({ _id: matches[0]._id }, buildLocalityUpdate(candidate, now));
      summary.localityUpdated++;
    }
  }

  for (const candidate of parentCandidates) {
    const query = parentQuery(candidate);
    const matches = await masterlocations.find(query, LOCK_PROJECTION).toArray();
    if (matches.length === 0) {
      summary.parentSkippedNoMatch++;
      problems.push({ type: "parent-no-match", candidate });
      continue;
    }
    if (matches.length > 1) {
      summary.parentSkippedDuplicateMatch++;
      problems.push({ type: "parent-duplicate-match", candidate, matches: matches.length });
      continue;
    }
    if (isLocked(matches[0])) {
      summary.parentSkippedLocked++;
      continue;
    }

    summary.parentMatched++;
    summary.parentWouldUpdate++;
    if (APPLY) {
      await masterlocations.updateOne({ _id: matches[0]._id }, buildParentUpdate(candidate, now));
      summary.parentUpdated++;
    }
  }

  console.log(JSON.stringify({ summary, problems: problems.slice(0, 50) }, null, 2));
  if (problems.length > 50) console.log(`Additional problems omitted: ${problems.length - 50}`);
  if (!APPLY) console.log("\nDry run only. Re-run with --apply to write these updates.");

  await client.close();
};

main().catch((error) => {
  console.error(error.stack || error.message);
  process.exit(1);
});
