// Redis Status
export const FETCH_REDIS_STATUS_REQUEST = "FETCH_REDIS_STATUS_REQUEST";
export const FETCH_REDIS_STATUS_SUCCESS = "FETCH_REDIS_STATUS_SUCCESS";
export const FETCH_REDIS_STATUS_FAILURE = "FETCH_REDIS_STATUS_FAILURE";

// Cache Invalidation
export const INVALIDATE_CACHE_REQUEST = "INVALIDATE_CACHE_REQUEST";
export const INVALIDATE_CACHE_SUCCESS = "INVALIDATE_CACHE_SUCCESS";
export const INVALIDATE_CACHE_FAILURE = "INVALIDATE_CACHE_FAILURE";

// Clear All Caches
export const CLEAR_ALL_CACHES_REQUEST = "CLEAR_ALL_CACHES_REQUEST";
export const CLEAR_ALL_CACHES_SUCCESS = "CLEAR_ALL_CACHES_SUCCESS";
export const CLEAR_ALL_CACHES_FAILURE = "CLEAR_ALL_CACHES_FAILURE";
