// Event Category Action Types
export const FETCH_EVENT_CATEGORY_REQUEST = "FETCH_EVENT_CATEGORY_REQUEST";
export const FETCH_EVENT_CATEGORY_SUCCESS = "FETCH_EVENT_CATEGORY_SUCCESS";
export const FETCH_EVENT_CATEGORY_FAILURE = "FETCH_EVENT_CATEGORY_FAILURE";

export const CREATE_EVENT_CATEGORY_REQUEST = "CREATE_EVENT_CATEGORY_REQUEST";
export const CREATE_EVENT_CATEGORY_SUCCESS = "CREATE_EVENT_CATEGORY_SUCCESS";
export const CREATE_EVENT_CATEGORY_FAILURE = "CREATE_EVENT_CATEGORY_FAILURE";

export const EDIT_EVENT_CATEGORY_REQUEST = "EDIT_EVENT_CATEGORY_REQUEST";
export const EDIT_EVENT_CATEGORY_SUCCESS = "EDIT_EVENT_CATEGORY_SUCCESS";
export const EDIT_EVENT_CATEGORY_FAILURE = "EDIT_EVENT_CATEGORY_FAILURE";

export const DELETE_EVENT_CATEGORY_REQUEST = "DELETE_EVENT_CATEGORY_REQUEST";
export const DELETE_EVENT_CATEGORY_SUCCESS = "DELETE_EVENT_CATEGORY_SUCCESS";
export const DELETE_EVENT_CATEGORY_FAILURE = "DELETE_EVENT_CATEGORY_FAILURE";

// Event Location Action Types
export const FETCH_EVENT_LOCATION_REQUEST = "FETCH_EVENT_LOCATION_REQUEST";
export const FETCH_EVENT_LOCATION_SUCCESS = "FETCH_EVENT_LOCATION_SUCCESS";
export const FETCH_EVENT_LOCATION_FAILURE = "FETCH_EVENT_LOCATION_FAILURE";

export const CREATE_EVENT_LOCATION_REQUEST = "CREATE_EVENT_LOCATION_REQUEST";
export const CREATE_EVENT_LOCATION_SUCCESS = "CREATE_EVENT_LOCATION_SUCCESS";
export const CREATE_EVENT_LOCATION_FAILURE = "CREATE_EVENT_LOCATION_FAILURE";

export const EDIT_EVENT_LOCATION_REQUEST = "EDIT_EVENT_LOCATION_REQUEST";
export const EDIT_EVENT_LOCATION_SUCCESS = "EDIT_EVENT_LOCATION_SUCCESS";
export const EDIT_EVENT_LOCATION_FAILURE = "EDIT_EVENT_LOCATION_FAILURE";

export const DELETE_EVENT_LOCATION_REQUEST = "DELETE_EVENT_LOCATION_REQUEST";
export const DELETE_EVENT_LOCATION_SUCCESS = "DELETE_EVENT_LOCATION_SUCCESS";
export const DELETE_EVENT_LOCATION_FAILURE = "DELETE_EVENT_LOCATION_FAILURE";

// Event Advertisement Action Types
export const FETCH_EVENT_ADVERTISEMENT_REQUEST = "FETCH_EVENT_ADVERTISEMENT_REQUEST";
export const FETCH_EVENT_ADVERTISEMENT_SUCCESS = "FETCH_EVENT_ADVERTISEMENT_SUCCESS";
export const FETCH_EVENT_ADVERTISEMENT_FAILURE = "FETCH_EVENT_ADVERTISEMENT_FAILURE";

export const CREATE_EVENT_ADVERTISEMENT_REQUEST = "CREATE_EVENT_ADVERTISEMENT_REQUEST";
export const CREATE_EVENT_ADVERTISEMENT_SUCCESS = "CREATE_EVENT_ADVERTISEMENT_SUCCESS";
export const CREATE_EVENT_ADVERTISEMENT_FAILURE = "CREATE_EVENT_ADVERTISEMENT_FAILURE";

export const EDIT_EVENT_ADVERTISEMENT_REQUEST = "EDIT_EVENT_ADVERTISEMENT_REQUEST";
export const EDIT_EVENT_ADVERTISEMENT_SUCCESS = "EDIT_EVENT_ADVERTISEMENT_SUCCESS";
export const EDIT_EVENT_ADVERTISEMENT_FAILURE = "EDIT_EVENT_ADVERTISEMENT_FAILURE";

export const DELETE_EVENT_ADVERTISEMENT_REQUEST = "DELETE_EVENT_ADVERTISEMENT_REQUEST";
export const DELETE_EVENT_ADVERTISEMENT_SUCCESS = "DELETE_EVENT_ADVERTISEMENT_SUCCESS";
export const DELETE_EVENT_ADVERTISEMENT_FAILURE = "DELETE_EVENT_ADVERTISEMENT_FAILURE";

// Event Creation Action Types
export const FETCH_EVENT_CREATION_REQUEST = "FETCH_EVENT_CREATION_REQUEST";
export const FETCH_EVENT_CREATION_SUCCESS = "FETCH_EVENT_CREATION_SUCCESS";
export const FETCH_EVENT_CREATION_FAILURE = "FETCH_EVENT_CREATION_FAILURE";

export const VIEW_EVENT_CREATION_REQUEST = "VIEW_EVENT_CREATION_REQUEST";
export const VIEW_EVENT_CREATION_SUCCESS = "VIEW_EVENT_CREATION_SUCCESS";
export const VIEW_EVENT_CREATION_FAILURE = "VIEW_EVENT_CREATION_FAILURE";

export const CREATE_EVENT_CREATION_REQUEST = "CREATE_EVENT_CREATION_REQUEST";
export const CREATE_EVENT_CREATION_SUCCESS = "CREATE_EVENT_CREATION_SUCCESS";
export const CREATE_EVENT_CREATION_FAILURE = "CREATE_EVENT_CREATION_FAILURE";

export const EDIT_EVENT_CREATION_REQUEST = "EDIT_EVENT_CREATION_REQUEST";
export const EDIT_EVENT_CREATION_SUCCESS = "EDIT_EVENT_CREATION_SUCCESS";
export const EDIT_EVENT_CREATION_FAILURE = "EDIT_EVENT_CREATION_FAILURE";

export const DELETE_EVENT_CREATION_REQUEST = "DELETE_EVENT_CREATION_REQUEST";
export const DELETE_EVENT_CREATION_SUCCESS = "DELETE_EVENT_CREATION_SUCCESS";
export const DELETE_EVENT_CREATION_FAILURE = "DELETE_EVENT_CREATION_FAILURE";

export const PUBLISH_EVENT_CREATION_REQUEST = "PUBLISH_EVENT_CREATION_REQUEST";
export const PUBLISH_EVENT_CREATION_SUCCESS = "PUBLISH_EVENT_CREATION_SUCCESS";
export const PUBLISH_EVENT_CREATION_FAILURE = "PUBLISH_EVENT_CREATION_FAILURE";
