export const FETCH_FCM_USERS_REQUEST = "FETCH_FCM_USERS_REQUEST";
export const FETCH_FCM_USERS_SUCCESS = "FETCH_FCM_USERS_SUCCESS";
export const FETCH_FCM_USERS_FAILURE = "FETCH_FCM_USERS_FAILURE";

export const SEND_FCM_MARKETING_REQUEST = "SEND_FCM_MARKETING_REQUEST";
export const SEND_FCM_MARKETING_SUCCESS = "SEND_FCM_MARKETING_SUCCESS";
export const SEND_FCM_MARKETING_FAILURE = "SEND_FCM_MARKETING_FAILURE";

export const SCHEDULE_FCM_MARKETING_REQUEST = "SCHEDULE_FCM_MARKETING_REQUEST";
export const SCHEDULE_FCM_MARKETING_SUCCESS = "SCHEDULE_FCM_MARKETING_SUCCESS";
export const SCHEDULE_FCM_MARKETING_FAILURE = "SCHEDULE_FCM_MARKETING_FAILURE";

export const RESEND_FCM_CAMPAIGN_REQUEST = "RESEND_FCM_CAMPAIGN_REQUEST";
export const RESEND_FCM_CAMPAIGN_SUCCESS = "RESEND_FCM_CAMPAIGN_SUCCESS";
export const RESEND_FCM_CAMPAIGN_FAILURE = "RESEND_FCM_CAMPAIGN_FAILURE";

export const CANCEL_FCM_CAMPAIGN_REQUEST = "CANCEL_FCM_CAMPAIGN_REQUEST";
export const CANCEL_FCM_CAMPAIGN_SUCCESS = "CANCEL_FCM_CAMPAIGN_SUCCESS";
export const CANCEL_FCM_CAMPAIGN_FAILURE = "CANCEL_FCM_CAMPAIGN_FAILURE";

export const FETCH_FCM_CAMPAIGNS_REQUEST = "FETCH_FCM_CAMPAIGNS_REQUEST";
export const FETCH_FCM_CAMPAIGNS_SUCCESS = "FETCH_FCM_CAMPAIGNS_SUCCESS";
export const FETCH_FCM_CAMPAIGNS_FAILURE = "FETCH_FCM_CAMPAIGNS_FAILURE";
