export const FETCH_GA4_OVERVIEW_REQUEST = "FETCH_GA4_OVERVIEW_REQUEST";
export const FETCH_GA4_OVERVIEW_SUCCESS = "FETCH_GA4_OVERVIEW_SUCCESS";
export const FETCH_GA4_OVERVIEW_FAILURE = "FETCH_GA4_OVERVIEW_FAILURE";

export const FETCH_GA4_TRENDS_REQUEST = "FETCH_GA4_TRENDS_REQUEST";
export const FETCH_GA4_TRENDS_SUCCESS = "FETCH_GA4_TRENDS_SUCCESS";
export const FETCH_GA4_TRENDS_FAILURE = "FETCH_GA4_TRENDS_FAILURE";

export const FETCH_GA4_TRAFFIC_SOURCES_REQUEST = "FETCH_GA4_TRAFFIC_SOURCES_REQUEST";
export const FETCH_GA4_TRAFFIC_SOURCES_SUCCESS = "FETCH_GA4_TRAFFIC_SOURCES_SUCCESS";
export const FETCH_GA4_TRAFFIC_SOURCES_FAILURE = "FETCH_GA4_TRAFFIC_SOURCES_FAILURE";

export const FETCH_GA4_LOCATIONS_REQUEST = "FETCH_GA4_LOCATIONS_REQUEST";
export const FETCH_GA4_LOCATIONS_SUCCESS = "FETCH_GA4_LOCATIONS_SUCCESS";
export const FETCH_GA4_LOCATIONS_FAILURE = "FETCH_GA4_LOCATIONS_FAILURE";

export const FETCH_GA4_DEVICES_REQUEST = "FETCH_GA4_DEVICES_REQUEST";
export const FETCH_GA4_DEVICES_SUCCESS = "FETCH_GA4_DEVICES_SUCCESS";
export const FETCH_GA4_DEVICES_FAILURE = "FETCH_GA4_DEVICES_FAILURE";

export const FETCH_GA4_CONVERSIONS_REQUEST = "FETCH_GA4_CONVERSIONS_REQUEST";
export const FETCH_GA4_CONVERSIONS_SUCCESS = "FETCH_GA4_CONVERSIONS_SUCCESS";
export const FETCH_GA4_CONVERSIONS_FAILURE = "FETCH_GA4_CONVERSIONS_FAILURE";

export const FETCH_GA4_CITIES_REQUEST = "FETCH_GA4_CITIES_REQUEST";
export const FETCH_GA4_CITIES_SUCCESS = "FETCH_GA4_CITIES_SUCCESS";
export const FETCH_GA4_CITIES_FAILURE = "FETCH_GA4_CITIES_FAILURE";

export const FETCH_GA4_BROWSERS_REQUEST = "FETCH_GA4_BROWSERS_REQUEST";
export const FETCH_GA4_BROWSERS_SUCCESS = "FETCH_GA4_BROWSERS_SUCCESS";
export const FETCH_GA4_BROWSERS_FAILURE = "FETCH_GA4_BROWSERS_FAILURE";

export const FETCH_GA4_PAGES_REQUEST = "FETCH_GA4_PAGES_REQUEST";
export const FETCH_GA4_PAGES_SUCCESS = "FETCH_GA4_PAGES_SUCCESS";
export const FETCH_GA4_PAGES_FAILURE = "FETCH_GA4_PAGES_FAILURE";

export const FETCH_GA4_LANDING_PAGES_REQUEST = "FETCH_GA4_LANDING_PAGES_REQUEST";
export const FETCH_GA4_LANDING_PAGES_SUCCESS = "FETCH_GA4_LANDING_PAGES_SUCCESS";
export const FETCH_GA4_LANDING_PAGES_FAILURE = "FETCH_GA4_LANDING_PAGES_FAILURE";

export const FETCH_GA4_ACQUISITION_REQUEST = "FETCH_GA4_ACQUISITION_REQUEST";
export const FETCH_GA4_ACQUISITION_SUCCESS = "FETCH_GA4_ACQUISITION_SUCCESS";
export const FETCH_GA4_ACQUISITION_FAILURE = "FETCH_GA4_ACQUISITION_FAILURE";

export const FETCH_GA4_ENGAGEMENT_OVERVIEW_REQUEST = "FETCH_GA4_ENGAGEMENT_OVERVIEW_REQUEST";
export const FETCH_GA4_ENGAGEMENT_OVERVIEW_SUCCESS = "FETCH_GA4_ENGAGEMENT_OVERVIEW_SUCCESS";
export const FETCH_GA4_ENGAGEMENT_OVERVIEW_FAILURE = "FETCH_GA4_ENGAGEMENT_OVERVIEW_FAILURE";

export const FETCH_GA4_ECOMMERCE_OVERVIEW_REQUEST = "FETCH_GA4_ECOMMERCE_OVERVIEW_REQUEST";
export const FETCH_GA4_ECOMMERCE_OVERVIEW_SUCCESS = "FETCH_GA4_ECOMMERCE_OVERVIEW_SUCCESS";
export const FETCH_GA4_ECOMMERCE_OVERVIEW_FAILURE = "FETCH_GA4_ECOMMERCE_OVERVIEW_FAILURE";

export const FETCH_GA4_TOP_ITEMS_REQUEST = "FETCH_GA4_TOP_ITEMS_REQUEST";
export const FETCH_GA4_TOP_ITEMS_SUCCESS = "FETCH_GA4_TOP_ITEMS_SUCCESS";
export const FETCH_GA4_TOP_ITEMS_FAILURE = "FETCH_GA4_TOP_ITEMS_FAILURE";

export const FETCH_GA4_REFERRERS_REQUEST = "FETCH_GA4_REFERRERS_REQUEST";
export const FETCH_GA4_REFERRERS_SUCCESS = "FETCH_GA4_REFERRERS_SUCCESS";
export const FETCH_GA4_REFERRERS_FAILURE = "FETCH_GA4_REFERRERS_FAILURE";

export const FETCH_GA4_CAMPAIGNS_REQUEST = "FETCH_GA4_CAMPAIGNS_REQUEST";
export const FETCH_GA4_CAMPAIGNS_SUCCESS = "FETCH_GA4_CAMPAIGNS_SUCCESS";
export const FETCH_GA4_CAMPAIGNS_FAILURE = "FETCH_GA4_CAMPAIGNS_FAILURE";

export const FETCH_GA4_OPERATING_SYSTEMS_REQUEST = "FETCH_GA4_OPERATING_SYSTEMS_REQUEST";
export const FETCH_GA4_OPERATING_SYSTEMS_SUCCESS = "FETCH_GA4_OPERATING_SYSTEMS_SUCCESS";
export const FETCH_GA4_OPERATING_SYSTEMS_FAILURE = "FETCH_GA4_OPERATING_SYSTEMS_FAILURE";

export const FETCH_GA4_PLATFORMS_REQUEST = "FETCH_GA4_PLATFORMS_REQUEST";
export const FETCH_GA4_PLATFORMS_SUCCESS = "FETCH_GA4_PLATFORMS_SUCCESS";
export const FETCH_GA4_PLATFORMS_FAILURE = "FETCH_GA4_PLATFORMS_FAILURE";

export const FETCH_GA4_DEVICE_MODELS_REQUEST = "FETCH_GA4_DEVICE_MODELS_REQUEST";
export const FETCH_GA4_DEVICE_MODELS_SUCCESS = "FETCH_GA4_DEVICE_MODELS_SUCCESS";
export const FETCH_GA4_DEVICE_MODELS_FAILURE = "FETCH_GA4_DEVICE_MODELS_FAILURE";

export const FETCH_GA4_SCREEN_RESOLUTIONS_REQUEST = "FETCH_GA4_SCREEN_RESOLUTIONS_REQUEST";
export const FETCH_GA4_SCREEN_RESOLUTIONS_SUCCESS = "FETCH_GA4_SCREEN_RESOLUTIONS_SUCCESS";
export const FETCH_GA4_SCREEN_RESOLUTIONS_FAILURE = "FETCH_GA4_SCREEN_RESOLUTIONS_FAILURE";

export const FETCH_GA4_REGIONS_REQUEST = "FETCH_GA4_REGIONS_REQUEST";
export const FETCH_GA4_REGIONS_SUCCESS = "FETCH_GA4_REGIONS_SUCCESS";
export const FETCH_GA4_REGIONS_FAILURE = "FETCH_GA4_REGIONS_FAILURE";

export const FETCH_GA4_CONTINENTS_REQUEST = "FETCH_GA4_CONTINENTS_REQUEST";
export const FETCH_GA4_CONTINENTS_SUCCESS = "FETCH_GA4_CONTINENTS_SUCCESS";
export const FETCH_GA4_CONTINENTS_FAILURE = "FETCH_GA4_CONTINENTS_FAILURE";

export const FETCH_GA4_SUB_CONTINENTS_REQUEST = "FETCH_GA4_SUB_CONTINENTS_REQUEST";
export const FETCH_GA4_SUB_CONTINENTS_SUCCESS = "FETCH_GA4_SUB_CONTINENTS_SUCCESS";
export const FETCH_GA4_SUB_CONTINENTS_FAILURE = "FETCH_GA4_SUB_CONTINENTS_FAILURE";

export const FETCH_GA4_NEW_VS_RETURNING_REQUEST = "FETCH_GA4_NEW_VS_RETURNING_REQUEST";
export const FETCH_GA4_NEW_VS_RETURNING_SUCCESS = "FETCH_GA4_NEW_VS_RETURNING_SUCCESS";
export const FETCH_GA4_NEW_VS_RETURNING_FAILURE = "FETCH_GA4_NEW_VS_RETURNING_FAILURE";

export const FETCH_GA4_DAY_OF_WEEK_REQUEST = "FETCH_GA4_DAY_OF_WEEK_REQUEST";
export const FETCH_GA4_DAY_OF_WEEK_SUCCESS = "FETCH_GA4_DAY_OF_WEEK_SUCCESS";
export const FETCH_GA4_DAY_OF_WEEK_FAILURE = "FETCH_GA4_DAY_OF_WEEK_FAILURE";

export const FETCH_GA4_HOUR_OF_DAY_REQUEST = "FETCH_GA4_HOUR_OF_DAY_REQUEST";
export const FETCH_GA4_HOUR_OF_DAY_SUCCESS = "FETCH_GA4_HOUR_OF_DAY_SUCCESS";
export const FETCH_GA4_HOUR_OF_DAY_FAILURE = "FETCH_GA4_HOUR_OF_DAY_FAILURE";

export const FETCH_GA4_SCREENS_REQUEST = "FETCH_GA4_SCREENS_REQUEST";
export const FETCH_GA4_SCREENS_SUCCESS = "FETCH_GA4_SCREENS_SUCCESS";
export const FETCH_GA4_SCREENS_FAILURE = "FETCH_GA4_SCREENS_FAILURE";
