export const FETCH_GA4_OVERVIEW_REQUEST = "FETCH_GA4_OVERVIEW_REQUEST";
export const FETCH_GA4_OVERVIEW_SUCCESS = "FETCH_GA4_OVERVIEW_SUCCESS";
export const FETCH_GA4_OVERVIEW_FAILURE = "FETCH_GA4_OVERVIEW_FAILURE";

export const FETCH_GA4_TRENDS_REQUEST = "FETCH_GA4_TRENDS_REQUEST";
export const FETCH_GA4_TRENDS_SUCCESS = "FETCH_GA4_TRENDS_SUCCESS";
export const FETCH_GA4_TRENDS_FAILURE = "FETCH_GA4_TRENDS_FAILURE";

export const FETCH_GA4_TRAFFIC_SOURCES_REQUEST = "FETCH_GA4_TRAFFIC_SOURCES_REQUEST";
export const FETCH_GA4_TRAFFIC_SOURCES_SUCCESS = "FETCH_GA4_TRAFFIC_SOURCES_SUCCESS";
export const FETCH_GA4_TRAFFIC_SOURCES_FAILURE = "FETCH_GA4_TRAFFIC_SOURCES_FAILURE";

export const FETCH_GA4_LOCATIONS_REQUEST = "FETCH_GA4_LOCATIONS_REQUEST";
export const FETCH_GA4_LOCATIONS_SUCCESS = "FETCH_GA4_LOCATIONS_SUCCESS";
export const FETCH_GA4_LOCATIONS_FAILURE = "FETCH_GA4_LOCATIONS_FAILURE";

export const FETCH_GA4_DEVICES_REQUEST = "FETCH_GA4_DEVICES_REQUEST";
export const FETCH_GA4_DEVICES_SUCCESS = "FETCH_GA4_DEVICES_SUCCESS";
export const FETCH_GA4_DEVICES_FAILURE = "FETCH_GA4_DEVICES_FAILURE";

export const FETCH_GA4_CONVERSIONS_REQUEST = "FETCH_GA4_CONVERSIONS_REQUEST";
export const FETCH_GA4_CONVERSIONS_SUCCESS = "FETCH_GA4_CONVERSIONS_SUCCESS";
export const FETCH_GA4_CONVERSIONS_FAILURE = "FETCH_GA4_CONVERSIONS_FAILURE";
