export const FETCH_GSC_OVERVIEW_REQUEST = "FETCH_GSC_OVERVIEW_REQUEST";
export const FETCH_GSC_OVERVIEW_SUCCESS = "FETCH_GSC_OVERVIEW_SUCCESS";
export const FETCH_GSC_OVERVIEW_FAILURE = "FETCH_GSC_OVERVIEW_FAILURE";

export const FETCH_GSC_TRENDS_REQUEST = "FETCH_GSC_TRENDS_REQUEST";
export const FETCH_GSC_TRENDS_SUCCESS = "FETCH_GSC_TRENDS_SUCCESS";
export const FETCH_GSC_TRENDS_FAILURE = "FETCH_GSC_TRENDS_FAILURE";

export const FETCH_GSC_QUERIES_REQUEST = "FETCH_GSC_QUERIES_REQUEST";
export const FETCH_GSC_QUERIES_SUCCESS = "FETCH_GSC_QUERIES_SUCCESS";
export const FETCH_GSC_QUERIES_FAILURE = "FETCH_GSC_QUERIES_FAILURE";

export const FETCH_GSC_PAGES_REQUEST = "FETCH_GSC_PAGES_REQUEST";
export const FETCH_GSC_PAGES_SUCCESS = "FETCH_GSC_PAGES_SUCCESS";
export const FETCH_GSC_PAGES_FAILURE = "FETCH_GSC_PAGES_FAILURE";

export const FETCH_GSC_DEVICES_REQUEST = "FETCH_GSC_DEVICES_REQUEST";
export const FETCH_GSC_DEVICES_SUCCESS = "FETCH_GSC_DEVICES_SUCCESS";
export const FETCH_GSC_DEVICES_FAILURE = "FETCH_GSC_DEVICES_FAILURE";

export const FETCH_GSC_COUNTRIES_REQUEST = "FETCH_GSC_COUNTRIES_REQUEST";
export const FETCH_GSC_COUNTRIES_SUCCESS = "FETCH_GSC_COUNTRIES_SUCCESS";
export const FETCH_GSC_COUNTRIES_FAILURE = "FETCH_GSC_COUNTRIES_FAILURE";

export const FETCH_GSC_OPPORTUNITIES_REQUEST = "FETCH_GSC_OPPORTUNITIES_REQUEST";
export const FETCH_GSC_OPPORTUNITIES_SUCCESS = "FETCH_GSC_OPPORTUNITIES_SUCCESS";
export const FETCH_GSC_OPPORTUNITIES_FAILURE = "FETCH_GSC_OPPORTUNITIES_FAILURE";

export const FETCH_GSC_KEYWORD_GAPS_REQUEST = "FETCH_GSC_KEYWORD_GAPS_REQUEST";
export const FETCH_GSC_KEYWORD_GAPS_SUCCESS = "FETCH_GSC_KEYWORD_GAPS_SUCCESS";
export const FETCH_GSC_KEYWORD_GAPS_FAILURE = "FETCH_GSC_KEYWORD_GAPS_FAILURE";

export const FETCH_TRACKED_KEYWORDS_REQUEST = "FETCH_TRACKED_KEYWORDS_REQUEST";
export const FETCH_TRACKED_KEYWORDS_SUCCESS = "FETCH_TRACKED_KEYWORDS_SUCCESS";
export const FETCH_TRACKED_KEYWORDS_FAILURE = "FETCH_TRACKED_KEYWORDS_FAILURE";

export const ADD_TRACKED_KEYWORD_REQUEST = "ADD_TRACKED_KEYWORD_REQUEST";
export const ADD_TRACKED_KEYWORD_SUCCESS = "ADD_TRACKED_KEYWORD_SUCCESS";
export const ADD_TRACKED_KEYWORD_FAILURE = "ADD_TRACKED_KEYWORD_FAILURE";

export const UPDATE_TRACKED_KEYWORD_SUCCESS = "UPDATE_TRACKED_KEYWORD_SUCCESS";
export const DELETE_TRACKED_KEYWORD_SUCCESS = "DELETE_TRACKED_KEYWORD_SUCCESS";

export const CHECK_KEYWORD_RANK_REQUEST = "CHECK_KEYWORD_RANK_REQUEST";
export const CHECK_KEYWORD_RANK_SUCCESS = "CHECK_KEYWORD_RANK_SUCCESS";
export const CHECK_KEYWORD_RANK_FAILURE = "CHECK_KEYWORD_RANK_FAILURE";

export const CHECK_ALL_KEYWORDS_REQUEST = "CHECK_ALL_KEYWORDS_REQUEST";
export const CHECK_ALL_KEYWORDS_SUCCESS = "CHECK_ALL_KEYWORDS_SUCCESS";
export const CHECK_ALL_KEYWORDS_FAILURE = "CHECK_ALL_KEYWORDS_FAILURE";

export const FETCH_KEYWORD_HISTORY_REQUEST = "FETCH_KEYWORD_HISTORY_REQUEST";
export const FETCH_KEYWORD_HISTORY_SUCCESS = "FETCH_KEYWORD_HISTORY_SUCCESS";
export const FETCH_KEYWORD_HISTORY_FAILURE = "FETCH_KEYWORD_HISTORY_FAILURE";

export const FETCH_KEYWORD_QUOTA_SUCCESS = "FETCH_KEYWORD_QUOTA_SUCCESS";
