export const FETCH_MSG91_DASHBOARD_REQUEST = "FETCH_MSG91_DASHBOARD_REQUEST";
export const FETCH_MSG91_DASHBOARD_SUCCESS = "FETCH_MSG91_DASHBOARD_SUCCESS";
export const FETCH_MSG91_DASHBOARD_FAILURE = "FETCH_MSG91_DASHBOARD_FAILURE";

export const FETCH_MSG91_AUDIT_REQUEST = "FETCH_MSG91_AUDIT_REQUEST";
export const FETCH_MSG91_AUDIT_SUCCESS = "FETCH_MSG91_AUDIT_SUCCESS";
export const FETCH_MSG91_AUDIT_FAILURE = "FETCH_MSG91_AUDIT_FAILURE";

export const FETCH_MSG91_RECIPIENTS_REQUEST = "FETCH_MSG91_RECIPIENTS_REQUEST";
export const FETCH_MSG91_RECIPIENTS_SUCCESS = "FETCH_MSG91_RECIPIENTS_SUCCESS";
export const FETCH_MSG91_RECIPIENTS_FAILURE = "FETCH_MSG91_RECIPIENTS_FAILURE";

export const UPDATE_MSG91_RECIPIENT_SUCCESS = "UPDATE_MSG91_RECIPIENT_SUCCESS";
