export const FETCH_SYSTEM_SETTINGS_REQUEST = "FETCH_SYSTEM_SETTINGS_REQUEST";
export const FETCH_SYSTEM_SETTINGS_SUCCESS = "FETCH_SYSTEM_SETTINGS_SUCCESS";
export const FETCH_SYSTEM_SETTINGS_FAILURE = "FETCH_SYSTEM_SETTINGS_FAILURE";

export const UPDATE_SYSTEM_SETTINGS_REQUEST = "UPDATE_SYSTEM_SETTINGS_REQUEST";
export const UPDATE_SYSTEM_SETTINGS_SUCCESS = "UPDATE_SYSTEM_SETTINGS_SUCCESS";
export const UPDATE_SYSTEM_SETTINGS_FAILURE = "UPDATE_SYSTEM_SETTINGS_FAILURE";
