
//User

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

//Client
export const CREATE_USERCLIENT_REQUEST = "CREATE_USERCLIENT_REQUEST";
export const CREATE_USERCLIENT_SUCCESS = "CREATE_USERCLIENT_SUCCESS";
export const CREATE_USERCLIENT_FAILURE = "CREATE_USERCLIENT_FAILURE";

export const FETCH_USERSCLIENT_REQUEST = "FETCH_USERSCLIENT_REQUEST";
export const FETCH_USERSCLIENT_SUCCESS = "FETCH_USERSCLIENT_SUCCESS";
export const FETCH_USERSCLIENT_FAILURE = "FETCH_USERSCLIENT_FAILURE";

export const EDIT_USERCLIENT_REQUEST = "EDIT_USERCLIENT_REQUEST";
export const EDIT_USERCLIENT_SUCCESS = "EDIT_USERCLIENT_SUCCESS";
export const EDIT_USERCLIENT_FAILURE = "EDIT_USERCLIENT_FAILURE";

export const DELETE_USERCLIENT_REQUEST = "DELETE_USERCLIENT_REQUEST";
export const DELETE_USERCLIENT_SUCCESS = "DELETE_USERCLIENT_SUCCESS";
export const DELETE_USERCLIENT_FAILURE = "DELETE_USERCLIENT_FAILURE";

//Quotation
export const CREATE_QUOTATION_REQUEST = "CREATE_QUOTATION_REQUEST";
export const CREATE_QUOTATION_SUCCESS = "CREATE_QUOTATION_SUCCESS";
export const CREATE_QUOTATION_FAILURE = "CREATE_QUOTATION_FAILURE";

export const FETCH_QUOTATION_REQUEST = "FETCH_QUOTATION_REQUEST";
export const FETCH_QUOTATION_SUCCESS = "FETCH_QUOTATION_SUCCESS";
export const FETCH_QUOTATION_FAILURE = "FETCH_QUOTATION_FAILURE";

export const EDIT_QUOTATION_REQUEST = "EDIT_QUOTATION_REQUEST";
export const EDIT_QUOTATION_SUCCESS = "EDIT_QUOTATION_SUCCESS";
export const EDIT_QUOTATION_FAILURE = "EDIT_QUOTATION_FAILURE";

export const DELETE_QUOTATION_REQUEST = "DELETE_QUOTATION_REQUEST";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAILURE = "DELETE_QUOTATION_FAILURE";

//Location
export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAILURE = "CREATE_LOCATION_FAILURE";

export const FETCH_LOCATION_REQUEST = "FETCH_LOCATION_REQUEST";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";

export const EDIT_LOCATION_REQUEST = "EDIT_LOCATION_REQUEST";
export const EDIT_LOCATION_SUCCESS = "EDIT_LOCATION_SUCCESS";
export const EDIT_LOCATION_FAILURE = "EDIT_LOCATION_FAILURE";

export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILURE = "DELETE_LOCATION_FAILURE";

//CATEGORY
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILURE = "EDIT_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const FETCH_CATEGORY_KEYWORDS_REQUEST = "FETCH_CATEGORY_KEYWORDS_REQUEST";
export const FETCH_CATEGORY_KEYWORDS_SUCCESS = "FETCH_CATEGORY_KEYWORDS_SUCCESS";
export const FETCH_CATEGORY_KEYWORDS_FAILURE = "FETCH_CATEGORY_KEYWORDS_FAILURE";


//BusinessList
export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAILURE = "CREATE_BUSINESS_FAILURE";

export const FETCH_BUSINESS_REQUEST = "FETCH_BUSINESS_REQUEST";
export const FETCH_BUSINESS_SUCCESS = "FETCH_BUSINESS_SUCCESS";
export const FETCH_BUSINESS_FAILURE = "FETCH_BUSINESS_FAILURE";

export const EXPORT_BUSINESS_REQUEST = "EXPORT_BUSINESS_REQUEST";
export const EXPORT_BUSINESS_SUCCESS = "EXPORT_BUSINESS_SUCCESS";
export const EXPORT_BUSINESS_FAILURE = "EXPORT_BUSINESS_FAILURE";

export const FETCH_VIEWBUSINESS_REQUEST = "FETCH_VIEWBUSINESS_REQUEST";
export const FETCH_VIEWBUSINESS_SUCCESS = "FETCH_VIEWBUSINESS_SUCCESS";
export const FETCH_VIEWBUSINESS_FAILURE = "FETCH_VIEWBUSINESS_FAILURE";

export const FETCH_VIEWBUSINESSDETAILS_REQUEST = "FETCH_VIEWBUSINESSDETAILS_REQUEST";
export const FETCH_VIEWBUSINESSDETAILS_SUCCESS = "FETCH_VIEWBUSINESSDETAILS_SUCCESS";
export const FETCH_VIEWBUSINESSDETAILS_FAILURE = "FETCH_VIEWBUSINESSDETAILS_FAILURE";

export const FETCH_DASHBOARDCARD_REQUEST = "FETCH_DASHBOARDCARD_REQUEST";
export const FETCH_DASHBOARDCARD_SUCCESS = "FETCH_DASHBOARDCARD_SUCCESS";
export const FETCH_DASHBOARDCARD_FAILURE = "FETCH_DASHBOARDCARD_FAILURE";

export const FETCH_DASHBOARDCHART_REQUEST = "FETCH_DASHBOARDCHART_REQUEST";
export const FETCH_DASHBOARDCHART_SUCCESS = "FETCH_DASHBOARDCHART_SUCCESS";
export const FETCH_DASHBOARDCHART_FAILURE = "FETCH_DASHBOARDCHART_FAILURE";

export const EDIT_BUSINESS_REQUEST = "EDIT_BUSINESS_REQUEST";
export const EDIT_BUSINESS_SUCCESS = "EDIT_BUSINESS_SUCCESS";
export const EDIT_BUSINESS_FAILURE = "EDIT_BUSINESS_FAILURE";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAILURE = "DELETE_BUSINESS_FAILURE";

export const ACTIVE_BUSINESS_REQUEST = "ACTIVE_BUSINESS_REQUEST";
export const ACTIVE_BUSINESS_SUCCESS = "ACTIVE_BUSINESS_SUCCESS";
export const ACTIVE_BUSINESS_FAILURE = "ACTIVE_BUSINESS_FAILURE";

export const FETCH_TRENDING_REQUEST = 'FETCH_TRENDING_REQUEST';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE';

export const FETCH_LOGS_REQUEST = "FETCH_LOGS_REQUEST";
export const FETCH_LOGS_SUCCESS = "FETCH_LOGS_SUCCESS";
export const FETCH_LOGS_FAILURE = "FETCH_LOGS_FAILURE";

export const FETCH_SEARCH_LOGS_REQUEST = "FETCH_SEARCH_LOGS_REQUEST";
export const FETCH_SEARCH_LOGS_SUCCESS = "FETCH_SEARCH_LOGS_SUCCESS";
export const FETCH_SEARCH_LOGS_FAILURE = "FETCH_SEARCH_LOGS_FAILURE";

//Roles
export const CREATE_ROLES_REQUEST = "CREATE_ROLES_REQUEST";
export const CREATE_ROLES_SUCCESS = "CREATE_ROLES_SUCCESS";
export const CREATE_ROLES_FAILURE = "CREATE_ROLES_FAILURE";

export const FETCH_ROLES_REQUEST = "FETCH_ROLES_REQUEST";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";

export const EDIT_ROLES_REQUEST = "EDIT_ROLES_REQUEST";
export const EDIT_ROLES_SUCCESS = "EDIT_ROLES_SUCCESS";
export const EDIT_ROLES_FAILURE = "EDIT_ROLES_FAILURE";

export const DELETE_ROLES_REQUEST = "DELETE_ROLES_REQUEST";
export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export const DELETE_ROLES_FAILURE = "DELETE_ROLES_FAILURE";

//Enquiry
export const CREATE_ENQUIRY_REQUEST = "CREATE_ENQUIRY_REQUEST";
export const CREATE_ENQUIRY_SUCCESS = "CREATE_ENQUIRY_SUCCESS";
export const CREATE_ENQUIRY_FAILURE = "CREATE_ENQUIRY_FAILURE";

export const FETCH_ENQUIRY_REQUEST = "FETCH_ENQUIRY_REQUEST";
export const FETCH_ENQUIRY_SUCCESS = "FETCH_ENQUIRY_SUCCESS";
export const FETCH_ENQUIRY_FAILURE = "FETCH_ENQUIRY_FAILURE";

export const EDIT_ENQUIRY_REQUEST = "EDIT_ENQUIRY_REQUEST";
export const EDIT_ENQUIRY_SUCCESS = "EDIT_ENQUIRY_SUCCESS";
export const EDIT_ENQUIRY_FAILURE = "EDIT_ENQUIRY_FAILURE";

export const DELETE_ENQUIRY_REQUEST = "DELETE_ENQUIRY_REQUEST";
export const DELETE_ENQUIRY_SUCCESS = "DELETE_ENQUIRY_SUCCESS";
export const DELETE_ENQUIRY_FAILURE = "DELETE_ENQUIRY_FAILURE";

//Start Project
export const CREATE_STARTPROJECT_REQUEST = "CREATE_STARTPROJECT_REQUEST";
export const CREATE_STARTPROJECT_SUCCESS = "CREATE_STARTPROJECT_SUCCESS";
export const CREATE_STARTPROJECT_FAILURE = "CREATE_STARTPROJECT_FAILURE";

export const FETCH_STARTPROJECT_REQUEST = "FETCH_STARTPROJECT_REQUEST";
export const FETCH_STARTPROJECT_SUCCESS = "FETCH_STARTPROJECT_SUCCESS";
export const FETCH_STARTPROJECT_FAILURE = "FETCH_STARTPROJECT_FAILURE";

export const EDIT_STARTPROJECT_REQUEST = "EDIT_STARTPROJECT_REQUEST";
export const EDIT_STARTPROJECT_SUCCESS = "EDIT_STARTPROJECT_SUCCESS";
export const EDIT_STARTPROJECT_FAILURE = "EDIT_STARTPROJECT_FAILURE";

export const DELETE_STARTPROJECT_REQUEST = "DELETE_STARTPROJECT_REQUEST";
export const DELETE_STARTPROJECT_SUCCESS = "DELETE_STARTPROJECT_SUCCESS";
export const DELETE_STARTPROJECT_FAILURE = "DELETE_STARTPROJECT_FAILURE";


//Otp users
export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const UPDATE_OTP_USER_REQUEST = "UPDATE_OTP_USER_REQUEST"
export const UPDATE_OTP_USER_SUCCESS = "UPDATE_OTP_USER_SUCCESS"
export const UPDATE_OTP_USER_FAILURE = "UPDATE_OTP_USER_FAILURE"

export const VIEW_OTP_USER_REQUEST = "VIEW_OTP_USER_REQUEST"
export const VIEW_OTP_USER_SUCCESS = "VIEW_OTP_USER_SUCCESS"
export const VIEW_OTP_USER_FAILURE = "VIEW_OTP_USER_FAILURE"

export const VIEWALL_OTP_USER_REQUEST = "VIEWALL_OTP_USER_REQUEST"
export const VIEWALL_OTP_USER_SUCCESS = "VIEWALL_OTP_USER_SUCCESS"
export const VIEWALL_OTP_USER_FAILURE = "VIEWALL_OTP_USER_FAILURE"

export const LOG_USER_SEARCH_REQUEST = "LOG_USER_SEARCH_REQUEST";
export const LOG_USER_SEARCH_SUCCESS = "LOG_USER_SEARCH_SUCCESS";
export const LOG_USER_SEARCH_FAILURE = "LOG_USER_SEARCH_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

//PhonePay
export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";

export const CHECK_PAYMENT_STATUS_REQUEST = "CHECK_PAYMENT_STATUS_REQUEST";
export const CHECK_PAYMENT_STATUS_SUCCESS = "CHECK_PAYMENT_STATUS_SUCCESS";
export const CHECK_PAYMENT_STATUS_FAILURE = "CHECK_PAYMENT_STATUS_FAILURE";

//IpLocation
export const FETCH_IP_LOCATION_REQUEST = "FETCH_IP_LOCATION_REQUEST";
export const FETCH_IP_LOCATION_SUCCESS = "FETCH_IP_LOCATION_SUCCESS";
export const FETCH_IP_LOCATION_FAILURE = "FETCH_IP_LOCATION_FAILURE";

//Search
export const SEARCH_BUSINESS_REQUEST = "SEARCH_BUSINESS_REQUEST";
export const SEARCH_BUSINESS_SUCCESS = "SEARCH_BUSINESS_SUCCESS";
export const SEARCH_BUSINESS_FAILURE = "SEARCH_BUSINESS_FAILURE";

//Suggestion
export const SUGGESTION_BUSINESS_REQUEST = "SUGGESTION_BUSINESS_REQUEST";
export const SUGGESTION_BUSINESS_SUCCESS = "SUGGESTION_BUSINESS_SUCCESS";
export const SUGGESTION_BUSINESS_FAILURE = "SUGGESTION_BUSINESS_FAILURE";

export const CATEGORY_BUSINESS_REQUEST = "CATEGORY_BUSINESS_REQUEST";
export const CATEGORY_BUSINESS_SUCCESS = "CATEGORY_BUSINESS_SUCCESS";
export const CATEGORY_BUSINESS_FAILURE = "CATEGORY_BUSINESS_FAILURE";



export const SET_LEADS_HISTORY_USERS = "SET_LEADS_HISTORY_USERS";


export const FIND_BUSINESS_BY_MOBILE_REQUEST = "FIND_BUSINESS_BY_MOBILE_REQUEST";
export const FIND_BUSINESS_BY_MOBILE_SUCCESS = "FIND_BUSINESS_BY_MOBILE_SUCCESS";
export const FIND_BUSINESS_BY_MOBILE_FAILURE = "FIND_BUSINESS_BY_MOBILE_FAILURE";

export const SEARCH_USERCLIENTSSUGGESTION_REQUEST = "SEARCH_USERCLIENTSSUGGESTION_REQUEST";
export const SEARCH_USERCLIENTSSUGGESTION_SUCCESS = "SEARCH_USERCLIENTSSUGGESTION_SUCCESS";
export const SEARCH_USERCLIENTSSUGGESTION_FAILURE = "SEARCH_USERCLIENTSSUGGESTION_FAILURE";

export const FETCH_PENDINGBUSINESS_REQUEST = "FETCH_PENDINGBUSINESS_REQUEST";
export const FETCH_PENDINGBUSINESS_SUCCESS = "FETCH_PENDINGBUSINESS_SUCCESS";
export const FETCH_PENDINGBUSINESS_FAILURE = "FETCH_PENDINGBUSINESS_FAILURE";

export const BUSINESS_CATEGORYSEARCH_REQUEST = "BUSINESS_CATEGORYSEARCH_REQUEST";
export const BUSINESS_CATEGORYSEARCH_SUCCESS = "BUSINESS_CATEGORYSEARCH_SUCCESS";
export const BUSINESS_CATEGORYSEARCH_FAILURE = "BUSINESS_CATEGORYSEARCH_FAILURE";

// whatsApp
export const SEND_WHATSAPP_REQUEST = "SEND_WHATSAPP_REQUEST";
export const SEND_WHATSAPP_SUCCESS = "SEND_WHATSAPP_SUCCESS";
export const SEND_WHATSAPP_FAILURE = "SEND_WHATSAPP_FAILURE";

export const SEND_WHATSAPP_ALL_REQUEST = "SEND_WHATSAPP_ALL_REQUEST";
export const SEND_WHATSAPP_ALL_SUCCESS = "SEND_WHATSAPP_ALL_SUCCESS";
export const SEND_WHATSAPP_ALL_FAILURE = "SEND_WHATSAPP_ALL_FAILURE";

// send enquiry lead (category/business)
export const SEND_ENQUIRY_LEAD_REQUEST = "SEND_ENQUIRY_LEAD_REQUEST";
export const SEND_ENQUIRY_LEAD_SUCCESS = "SEND_ENQUIRY_LEAD_SUCCESS";
export const SEND_ENQUIRY_LEAD_FAILURE = "SEND_ENQUIRY_LEAD_FAILURE";

//filterLeads
export const SET_FILTERED_LEADS = "SET_FILTERED_LEADS";
export const SET_ALL_LEADS = "SET_ALL_LEADS";
export const SET_MATCHED_LEADS = "SET_MATCHED_LEADS";

export const MATCH_LEADS_REQUEST = "MATCH_LEADS_REQUEST";
export const MATCH_LEADS_SUCCESS = "MATCH_LEADS_SUCCESS";
export const MATCH_LEADS_FAILURE = "MATCH_LEADS_FAILURE";

export const MATCH_LEADSVIEW_REQUEST = "MATCH_LEADSVIEW_REQUEST";
export const MATCH_LEADSVIEW_SUCCESS = "MATCH_LEADSVIEW_SUCCESS";
export const MATCH_LEADSVIEW_FAILURE = "MATCH_LEADSVIEW_FAILURE";

//Advertisement
export const FETCH_AD_REQUEST = "FETCH_AD_REQUEST";
export const FETCH_AD_SUCCESS = "FETCH_AD_SUCCESS";
export const FETCH_AD_FAILURE = "FETCH_AD_FAILURE";

export const CREATE_AD_REQUEST = "CREATE_AD_REQUEST";
export const CREATE_AD_SUCCESS = "CREATE_AD_SUCCESS";
export const CREATE_AD_FAILURE = "CREATE_AD_FAILURE";

export const EDIT_AD_REQUEST = "EDIT_AD_REQUEST";
export const EDIT_AD_SUCCESS = "EDIT_AD_SUCCESS";
export const EDIT_AD_FAILURE = "EDIT_AD_FAILURE";

export const VIEWCATEGORY_AD_REQUEST = "VIEWCATEGORY_AD_REQUEST";
export const VIEWCATEGORY_AD_SUCCESS = "VIEWCATEGORY_AD_SUCCESS";
export const VIEWCATEGORY_AD_FAILURE = "VIEWCATEGORY_AD_FAILURE";

export const DELETE_AD_REQUEST = "DELETE_AD_REQUEST";
export const DELETE_AD_SUCCESS = "DELETE_AD_SUCCESS";
export const DELETE_AD_FAILURE = "DELETE_AD_FAILURE";

//Massclick Documents
export const FETCH_MASSCLICK_DOCUMENTS_REQUEST = "FETCH_MASSCLICK_DOCUMENTS_REQUEST";
export const FETCH_MASSCLICK_DOCUMENTS_SUCCESS = "FETCH_MASSCLICK_DOCUMENTS_SUCCESS";
export const FETCH_MASSCLICK_DOCUMENTS_FAILURE = "FETCH_MASSCLICK_DOCUMENTS_FAILURE";

export const CREATE_MASSCLICK_DOCUMENT_REQUEST = "CREATE_MASSCLICK_DOCUMENT_REQUEST";
export const CREATE_MASSCLICK_DOCUMENT_SUCCESS = "CREATE_MASSCLICK_DOCUMENT_SUCCESS";
export const CREATE_MASSCLICK_DOCUMENT_FAILURE = "CREATE_MASSCLICK_DOCUMENT_FAILURE";

export const EDIT_MASSCLICK_DOCUMENT_REQUEST = "EDIT_MASSCLICK_DOCUMENT_REQUEST";
export const EDIT_MASSCLICK_DOCUMENT_SUCCESS = "EDIT_MASSCLICK_DOCUMENT_SUCCESS";
export const EDIT_MASSCLICK_DOCUMENT_FAILURE = "EDIT_MASSCLICK_DOCUMENT_FAILURE";

export const DELETE_MASSCLICK_DOCUMENT_REQUEST = "DELETE_MASSCLICK_DOCUMENT_REQUEST";
export const DELETE_MASSCLICK_DOCUMENT_SUCCESS = "DELETE_MASSCLICK_DOCUMENT_SUCCESS";
export const DELETE_MASSCLICK_DOCUMENT_FAILURE = "DELETE_MASSCLICK_DOCUMENT_FAILURE";

//Massclick Feed
export const FETCH_MASSCLICK_FEED_REQUEST = "FETCH_MASSCLICK_FEED_REQUEST";
export const FETCH_MASSCLICK_FEED_SUCCESS = "FETCH_MASSCLICK_FEED_SUCCESS";
export const FETCH_MASSCLICK_FEED_FAILURE = "FETCH_MASSCLICK_FEED_FAILURE";

export const CREATE_MASSCLICK_FEED_POST_REQUEST = "CREATE_MASSCLICK_FEED_POST_REQUEST";
export const CREATE_MASSCLICK_FEED_POST_SUCCESS = "CREATE_MASSCLICK_FEED_POST_SUCCESS";
export const CREATE_MASSCLICK_FEED_POST_FAILURE = "CREATE_MASSCLICK_FEED_POST_FAILURE";

export const UPDATE_MASSCLICK_FEED_POST_SUCCESS = "UPDATE_MASSCLICK_FEED_POST_SUCCESS";
export const MASSCLICK_FEED_ACTION_FAILURE = "MASSCLICK_FEED_ACTION_FAILURE";

export const CREATE_USER_FEEDBACK_REQUEST = "CREATE_USER_FEEDBACK_REQUEST";
export const CREATE_USER_FEEDBACK_SUCCESS = "CREATE_USER_FEEDBACK_SUCCESS";
export const CREATE_USER_FEEDBACK_FAILURE = "CREATE_USER_FEEDBACK_FAILURE";
export const FETCH_USER_FEEDBACK_REQUEST = "FETCH_USER_FEEDBACK_REQUEST";
export const FETCH_USER_FEEDBACK_SUCCESS = "FETCH_USER_FEEDBACK_SUCCESS";
export const FETCH_USER_FEEDBACK_FAILURE = "FETCH_USER_FEEDBACK_FAILURE";
export const UPDATE_USER_FEEDBACK_SUCCESS = "UPDATE_USER_FEEDBACK_SUCCESS";
export const USER_FEEDBACK_ACTION_FAILURE = "USER_FEEDBACK_ACTION_FAILURE";

export const SET_RUNTIME_LEADS = "SET_RUNTIME_LEADS";
export const MARK_RUNTIME_LEAD_READ = "MARK_RUNTIME_LEAD_READ";

export const UPDATE_SEARCH_LOG_REQUEST = "UPDATE_SEARCH_LOG_REQUEST";
export const UPDATE_SEARCH_LOG_SUCCESS = "UPDATE_SEARCH_LOG_SUCCESS";
export const UPDATE_SEARCH_LOG_FAILURE = "UPDATE_SEARCH_LOG_FAILURE";


//SEO METADATA
export const FETCH_SEO_REQUEST = "FETCH_SEO_REQUEST";
export const FETCH_SEO_SUCCESS = "FETCH_SEO_SUCCESS";
export const FETCH_SEO_FAILURE = "FETCH_SEO_FAILURE";

export const CREATE_SEO_REQUEST = "CREATE_SEO_REQUEST";
export const CREATE_SEO_SUCCESS = "CREATE_SEO_SUCCESS";
export const CREATE_SEO_FAILURE = "CREATE_SEO_FAILURE";

export const EDIT_SEO_REQUEST = "EDIT_SEO_REQUEST";
export const EDIT_SEO_SUCCESS = "EDIT_SEO_SUCCESS";
export const EDIT_SEO_FAILURE = "EDIT_SEO_FAILURE";

export const DELETE_SEO_REQUEST = "DELETE_SEO_REQUEST";
export const DELETE_SEO_SUCCESS = "DELETE_SEO_SUCCESS";
export const DELETE_SEO_FAILURE = "DELETE_SEO_FAILURE";

export const FETCH_SEO_META_REQUEST = "FETCH_SEO_META_REQUEST";
export const FETCH_SEO_META_SUCCESS = "FETCH_SEO_META_SUCCESS";
export const FETCH_SEO_META_FAILURE = "FETCH_SEO_META_FAILURE";

//Seo PageContent
export const FETCH_SEOPAGECONTENT_REQUEST = "FETCH_SEOPAGECONTENT_REQUEST";
export const FETCH_SEOPAGECONTENT_SUCCESS = "FETCH_SEOPAGECONTENT_SUCCESS";
export const FETCH_SEOPAGECONTENT_FAILURE = "FETCH_SEOPAGECONTENT_FAILURE";

export const CREATE_SEOPAGECONTENT_REQUEST = "CREATE_SEOPAGECONTENT_REQUEST";
export const CREATE_SEOPAGECONTENT_SUCCESS = "CREATE_SEOPAGECONTENT_SUCCESS";
export const CREATE_SEOPAGECONTENT_FAILURE = "CREATE_SEOPAGECONTENT_FAILURE";

export const EDIT_SEOPAGECONTENT_REQUEST = "EDIT_SEOPAGECONTENT_REQUEST";
export const EDIT_SEOPAGECONTENT_SUCCESS = "EDIT_SEOPAGECONTENT_SUCCESS";
export const EDIT_SEOPAGECONTENT_FAILURE = "EDIT_SEOPAGECONTENT_FAILURE";

export const DELETE_SEOPAGECONTENT_REQUEST = "DELETE_SEOPAGECONTENT_REQUEST";
export const DELETE_SEOPAGECONTENT_SUCCESS = "DELETE_SEOPAGECONTENT_SUCCESS";
export const DELETE_SEOPAGECONTENT_FAILURE = "DELETE_SEOPAGECONTENT_FAILURE";

export const FETCH_SEOPAGECONTENT_META_REQUEST = "FETCH_SEOPAGECONTENT_META_REQUEST";
export const FETCH_SEOPAGECONTENT_META_SUCCESS = "FETCH_SEOPAGECONTENT_META_SUCCESS";
export const FETCH_SEOPAGECONTENT_META_FAILURE = "FETCH_SEOPAGECONTENT_META_FAILURE";

//Seo PageContent Blogs
export const FETCH_SEOPAGECONTENTBLOGS_REQUEST = "FETCH_SEOPAGECONTENTBLOGS_REQUEST";
export const FETCH_SEOPAGECONTENTBLOGS_SUCCESS = "FETCH_SEOPAGECONTENTBLOGS_SUCCESS";
export const FETCH_SEOPAGECONTENTBLOGS_FAILURE = "FETCH_SEOPAGECONTENTBLOGS_FAILURE";

//Seo Template
export const FETCH_SEOTEMPLATE_REQUEST = "FETCH_SEOTEMPLATE_REQUEST";
export const FETCH_SEOTEMPLATE_SUCCESS = "FETCH_SEOTEMPLATE_SUCCESS";
export const FETCH_SEOTEMPLATE_FAILURE = "FETCH_SEOTEMPLATE_FAILURE";

export const CREATE_SEOTEMPLATE_REQUEST = "CREATE_SEOTEMPLATE_REQUEST";
export const CREATE_SEOTEMPLATE_SUCCESS = "CREATE_SEOTEMPLATE_SUCCESS";
export const CREATE_SEOTEMPLATE_FAILURE = "CREATE_SEOTEMPLATE_FAILURE";

export const EDIT_SEOTEMPLATE_REQUEST = "EDIT_SEOTEMPLATE_REQUEST";
export const EDIT_SEOTEMPLATE_SUCCESS = "EDIT_SEOTEMPLATE_SUCCESS";
export const EDIT_SEOTEMPLATE_FAILURE = "EDIT_SEOTEMPLATE_FAILURE";

export const DELETE_SEOTEMPLATE_REQUEST = "DELETE_SEOTEMPLATE_REQUEST";
export const DELETE_SEOTEMPLATE_SUCCESS = "DELETE_SEOTEMPLATE_SUCCESS";
export const DELETE_SEOTEMPLATE_FAILURE = "DELETE_SEOTEMPLATE_FAILURE";

export const CREATE_SEOPAGECONTENTBLOGS_REQUEST = "CREATE_SEOPAGECONTENTBLOGS_REQUEST";
export const CREATE_SEOPAGECONTENTBLOGS_SUCCESS = "CREATE_SEOPAGECONTENTBLOGS_SUCCESS";
export const CREATE_SEOPAGECONTENTBLOGS_FAILURE = "CREATE_SEOPAGECONTENTBLOGS_FAILURE";

export const EDIT_SEOPAGECONTENTBLOGS_REQUEST = "EDIT_SEOPAGECONTENTBLOGS_REQUEST";
export const EDIT_SEOPAGECONTENTBLOGS_SUCCESS = "EDIT_SEOPAGECONTENTBLOGS_SUCCESS";
export const EDIT_SEOPAGECONTENTBLOGS_FAILURE = "EDIT_SEOPAGECONTENTBLOGS_FAILURE";

export const DELETE_SEOPAGECONTENTBLOGS_REQUEST = "DELETE_SEOPAGECONTENTBLOGS_REQUEST";
export const DELETE_SEOPAGECONTENTBLOGS_SUCCESS = "DELETE_SEOPAGECONTENTBLOGS_SUCCESS";
export const DELETE_SEOPAGECONTENTBLOGS_FAILURE = "DELETE_SEOPAGECONTENTBLOGS_FAILURE";

export const FETCH_SEOPAGECONTENTBLOGS_META_REQUEST = "FETCH_SEOPAGECONTENTBLOGS_META_REQUEST";
export const FETCH_SEOPAGECONTENTBLOGS_META_SUCCESS = "FETCH_SEOPAGECONTENTBLOGS_META_SUCCESS";
export const FETCH_SEOPAGECONTENTBLOGS_META_FAILURE = "FETCH_SEOPAGECONTENTBLOGS_META_FAILURE";

export const FETCH_SEOBLOG_BY_SLUG_REQUEST = "FETCH_SEOBLOG_BY_SLUG_REQUEST";
export const FETCH_SEOBLOG_BY_SLUG_SUCCESS = "FETCH_SEOBLOG_BY_SLUG_SUCCESS";
export const FETCH_SEOBLOG_BY_SLUG_FAILURE = "FETCH_SEOBLOG_BY_SLUG_FAILURE";

export const FETCH_BUSINESS_SUGGESTION_REQUEST = "FETCH_BUSINESS_SUGGESTION_REQUEST";
export const FETCH_BUSINESS_SUGGESTION_SUCCESS = "FETCH_BUSINESS_SUGGESTION_SUCCESS";
export const FETCH_BUSINESS_SUGGESTION_FAILURE = "FETCH_BUSINESS_SUGGESTION_FAILURE";

export const CLEAR_SEO_META = "CLEAR_SEO_META";

//MRPDatas

export const FETCH_MRP_REQUEST = 'FETCH_MRP_REQUEST';
export const FETCH_MRP_SUCCESS = 'FETCH_MRP_SUCCESS';
export const FETCH_MRP_FAILURE = 'FETCH_MRP_FAILURE';

export const CREATE_MRP_REQUEST = 'CREATE_MRP_REQUEST';
export const CREATE_MRP_SUCCESS = 'CREATE_MRP_SUCCESS';
export const CREATE_MRP_FAILURE = 'CREATE_MRP_FAILURE';

export const EDIT_MRP_REQUEST = 'EDIT_MRP_REQUEST';
export const EDIT_MRP_SUCCESS = 'EDIT_MRP_SUCCESS';
export const EDIT_MRP_FAILURE = 'EDIT_MRP_FAILURE';

export const DELETE_MRP_REQUEST = 'DELETE_MRP_REQUEST';
export const DELETE_MRP_SUCCESS = 'DELETE_MRP_SUCCESS';
export const DELETE_MRP_FAILURE = 'DELETE_MRP_FAILURE';

export const SEARCH_MRP_BUSINESS_REQUEST = "SEARCH_MRP_BUSINESS_REQUEST";
export const SEARCH_MRP_BUSINESS_SUCCESS = "SEARCH_MRP_BUSINESS_SUCCESS";
export const SEARCH_MRP_BUSINESS_FAILURE = "SEARCH_MRP_BUSINESS_FAILURE";

export const SEARCH_MRP_CATEGORY_REQUEST = "SEARCH_MRP_CATEGORY_REQUEST";
export const SEARCH_MRP_CATEGORY_SUCCESS = "SEARCH_MRP_CATEGORY_SUCCESS";
export const SEARCH_MRP_CATEGORY_FAILURE = "SEARCH_MRP_CATEGORY_FAILURE";

export const SEND_MRP_LEADS_REQUEST = "SEND_MRP_LEADS_REQUEST";
export const SEND_MRP_LEADS_SUCCESS = "SEND_MRP_LEADS_SUCCESS";
export const SEND_MRP_LEADS_FAILURE = "SEND_MRP_LEADS_FAILURE";

export const FETCH_MNI_LEADS_REQUEST = "FETCH_MNI_LEADS_REQUEST";
export const FETCH_MNI_LEADS_SUCCESS = "FETCH_MNI_LEADS_SUCCESS";
export const FETCH_MNI_LEADS_FAILURE = "FETCH_MNI_LEADS_FAILURE";

export const FETCH_BUSINESS_PROFILE_BY_PHONE_REQUEST = "FETCH_BUSINESS_PROFILE_BY_PHONE_REQUEST";
export const FETCH_BUSINESS_PROFILE_BY_PHONE_SUCCESS = "FETCH_BUSINESS_PROFILE_BY_PHONE_SUCCESS";
export const FETCH_BUSINESS_PROFILE_BY_PHONE_FAILURE = "FETCH_BUSINESS_PROFILE_BY_PHONE_FAILURE";

export const FETCH_LEAD_REPORT_REQUEST = "FETCH_LEAD_REPORT_REQUEST";
export const FETCH_LEAD_REPORT_SUCCESS = "FETCH_LEAD_REPORT_SUCCESS";
export const FETCH_LEAD_REPORT_FAILURE = "FETCH_LEAD_REPORT_FAILURE";

//EnquiryNowData

export const FETCH_ENQUIRYNOW_REQUEST = "FETCH_ENQUIRYNOW_REQUEST";
export const FETCH_ENQUIRYNOW_SUCCESS = "FETCH_ENQUIRYNOW_SUCCESS";
export const FETCH_ENQUIRYNOW_FAILURE = "FETCH_ENQUIRYNOW_FAILURE";

export const CREATE_ENQUIRYNOW_REQUEST = "CREATE_ENQUIRYNOW_REQUEST";
export const CREATE_ENQUIRYNOW_SUCCESS = "CREATE_ENQUIRYNOW_SUCCESS";
export const CREATE_ENQUIRYNOW_FAILURE = "CREATE_ENQUIRYNOW_FAILURE";

//slug-request
export const FETCH_BUSINESS_BY_SLUG_REQUEST = "FETCH_BUSINESS_BY_SLUG_REQUEST";
export const FETCH_BUSINESS_BY_SLUG_SUCCESS = "FETCH_BUSINESS_BY_SLUG_SUCCESS";
export const FETCH_BUSINESS_BY_SLUG_FAILURE = "FETCH_BUSINESS_BY_SLUG_FAILURE";

//seo-category-suggestion
export const FETCH_SEO_CATEGORY_SUGGESTIONS_REQUEST = "FETCH_SEO_CATEGORY_SUGGESTIONS_REQUEST";
export const FETCH_SEO_CATEGORY_SUGGESTIONS_SUCCESS = "FETCH_SEO_CATEGORY_SUGGESTIONS_SUCCESS";
export const FETCH_SEO_CATEGORY_SUGGESTIONS_FAILURE = "FETCH_SEO_CATEGORY_SUGGESTIONS_FAILURE";

// Business-Reviews

export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "FETCH_REVIEWS_FAILURE";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";

export const REPLY_REVIEW_REQUEST = "REPLY_REVIEW_REQUEST";
export const REPLY_REVIEW_SUCCESS = "REPLY_REVIEW_SUCCESS";
export const REPLY_REVIEW_FAILURE = "REPLY_REVIEW_FAILURE";

export const HELPFUL_REVIEW_REQUEST = "HELPFUL_REVIEW_REQUEST";
export const HELPFUL_REVIEW_SUCCESS = "HELPFUL_REVIEW_SUCCESS";
export const HELPFUL_REVIEW_FAILURE = "HELPFUL_REVIEW_FAILURE";

export const REPORT_REVIEW_REQUEST = "REPORT_REVIEW_REQUEST";
export const REPORT_REVIEW_SUCCESS = "REPORT_REVIEW_SUCCESS";
export const REPORT_REVIEW_FAILURE = "REPORT_REVIEW_FAILURE";

// Detect District (GPS based)
export const DETECT_DISTRICT_REQUEST = "DETECT_DISTRICT_REQUEST";
export const DETECT_DISTRICT_SUCCESS = "DETECT_DISTRICT_SUCCESS";
export const DETECT_DISTRICT_FAILURE = "DETECT_DISTRICT_FAILURE";

// Master Location (hierarchical location master)
export const FETCH_MASTER_LOCATION_REQUEST = "FETCH_MASTER_LOCATION_REQUEST";
export const FETCH_MASTER_LOCATION_SUCCESS = "FETCH_MASTER_LOCATION_SUCCESS";
export const FETCH_MASTER_LOCATION_FAILURE = "FETCH_MASTER_LOCATION_FAILURE";

export const CREATE_MASTER_LOCATION_REQUEST = "CREATE_MASTER_LOCATION_REQUEST";
export const CREATE_MASTER_LOCATION_SUCCESS = "CREATE_MASTER_LOCATION_SUCCESS";
export const CREATE_MASTER_LOCATION_FAILURE = "CREATE_MASTER_LOCATION_FAILURE";

export const EDIT_MASTER_LOCATION_REQUEST = "EDIT_MASTER_LOCATION_REQUEST";
export const EDIT_MASTER_LOCATION_SUCCESS = "EDIT_MASTER_LOCATION_SUCCESS";
export const EDIT_MASTER_LOCATION_FAILURE = "EDIT_MASTER_LOCATION_FAILURE";

export const DELETE_MASTER_LOCATION_REQUEST = "DELETE_MASTER_LOCATION_REQUEST";
export const DELETE_MASTER_LOCATION_SUCCESS = "DELETE_MASTER_LOCATION_SUCCESS";
export const DELETE_MASTER_LOCATION_FAILURE = "DELETE_MASTER_LOCATION_FAILURE";

export const SEARCH_MASTER_LOCATION_REQUEST = "SEARCH_MASTER_LOCATION_REQUEST";
export const SEARCH_MASTER_LOCATION_SUCCESS = "SEARCH_MASTER_LOCATION_SUCCESS";
export const SEARCH_MASTER_LOCATION_FAILURE = "SEARCH_MASTER_LOCATION_FAILURE";

//Qr Download
export const QR_DOWNLOAD_REQUEST = "QR_DOWNLOAD_REQUEST";
export const QR_DOWNLOAD_SUCCESS = "QR_DOWNLOAD_SUCCESS";
export const QR_DOWNLOAD_FAILURE = "QR_DOWNLOAD_FAILURE";

export const FETCH_PUBLICIZE_REQUEST = "FETCH_PUBLICIZE_REQUEST";
export const FETCH_PUBLICIZE_SUCCESS = "FETCH_PUBLICIZE_SUCCESS";
export const FETCH_PUBLICIZE_FAILURE = "FETCH_PUBLICIZE_FAILURE";

export const CREATE_PUBLICIZE_REQUEST = "CREATE_PUBLICIZE_REQUEST";
export const CREATE_PUBLICIZE_SUCCESS = "CREATE_PUBLICIZE_SUCCESS";
export const CREATE_PUBLICIZE_FAILURE = "CREATE_PUBLICIZE_FAILURE";

export const EDIT_PUBLICIZE_REQUEST = "EDIT_PUBLICIZE_REQUEST";
export const EDIT_PUBLICIZE_SUCCESS = "EDIT_PUBLICIZE_SUCCESS";
export const EDIT_PUBLICIZE_FAILURE = "EDIT_PUBLICIZE_FAILURE";

export const DELETE_PUBLICIZE_REQUEST = "DELETE_PUBLICIZE_REQUEST";
export const DELETE_PUBLICIZE_SUCCESS = "DELETE_PUBLICIZE_SUCCESS";
export const DELETE_PUBLICIZE_FAILURE = "DELETE_PUBLICIZE_FAILURE";

// HOME
export const FETCH_HOME_CATEGORY_REQUEST = "FETCH_HOME_CATEGORY_REQUEST";
export const FETCH_HOME_CATEGORY_SUCCESS = "FETCH_HOME_CATEGORY_SUCCESS";
export const FETCH_HOME_CATEGORY_FAILURE = "FETCH_HOME_CATEGORY_FAILURE";

// SUB
export const FETCH_SUB_CATEGORY_REQUEST = "FETCH_SUB_CATEGORY_REQUEST";
export const FETCH_SUB_CATEGORY_SUCCESS = "FETCH_SUB_CATEGORY_SUCCESS";
export const FETCH_SUB_CATEGORY_FAILURE = "FETCH_SUB_CATEGORY_FAILURE";

// POPULAR
export const FETCH_POPULAR_CATEGORY_REQUEST = "FETCH_POPULAR_CATEGORY_REQUEST";
export const FETCH_POPULAR_CATEGORY_SUCCESS = "FETCH_POPULAR_CATEGORY_SUCCESS";
export const FETCH_POPULAR_CATEGORY_FAILURE = "FETCH_POPULAR_CATEGORY_FAILURE";

export const FETCH_SERVICE_CARDS_REQUEST = "FETCH_SERVICE_CARDS_REQUEST";
export const FETCH_SERVICE_CARDS_SUCCESS = "FETCH_SERVICE_CARDS_SUCCESS";
export const FETCH_SERVICE_CARDS_FAILURE = "FETCH_SERVICE_CARDS_FAILURE";

// POPULAR SEARCHES (home section cards)
export const FETCH_POPULAR_SEARCHES_REQUEST = "FETCH_POPULAR_SEARCHES_REQUEST";
export const FETCH_POPULAR_SEARCHES_SUCCESS = "FETCH_POPULAR_SEARCHES_SUCCESS";
export const FETCH_POPULAR_SEARCHES_FAILURE = "FETCH_POPULAR_SEARCHES_FAILURE";

// TOP TOURIST PLACES
export const FETCH_TOP_TOURIST_REQUEST = "FETCH_TOP_TOURIST_REQUEST";
export const FETCH_TOP_TOURIST_SUCCESS = "FETCH_TOP_TOURIST_SUCCESS";
export const FETCH_TOP_TOURIST_FAILURE = "FETCH_TOP_TOURIST_FAILURE";

// POPULAR CATEGORY CONTENT (tabs + services + link sections)
export const FETCH_POPULAR_CATEGORY_CONTENT_REQUEST = "FETCH_POPULAR_CATEGORY_CONTENT_REQUEST";
export const FETCH_POPULAR_CATEGORY_CONTENT_SUCCESS = "FETCH_POPULAR_CATEGORY_CONTENT_SUCCESS";
export const FETCH_POPULAR_CATEGORY_CONTENT_FAILURE = "FETCH_POPULAR_CATEGORY_CONTENT_FAILURE";

// FOOTERS CONTENTS

// src/redux/actions/userActionTypes.js

export const FETCH_TERMS_REQUEST = "FETCH_TERMS_REQUEST";
export const FETCH_TERMS_SUCCESS = "FETCH_TERMS_SUCCESS";
export const FETCH_TERMS_FAILURE = "FETCH_TERMS_FAILURE";

export const CREATE_TERMS_REQUEST = "CREATE_TERMS_REQUEST";
export const CREATE_TERMS_SUCCESS = "CREATE_TERMS_SUCCESS";
export const CREATE_TERMS_FAILURE = "CREATE_TERMS_FAILURE";

export const EDIT_TERMS_REQUEST = "EDIT_TERMS_REQUEST";
export const EDIT_TERMS_SUCCESS = "EDIT_TERMS_SUCCESS";
export const EDIT_TERMS_FAILURE = "EDIT_TERMS_FAILURE";

export const DELETE_TERMS_REQUEST = "DELETE_TERMS_REQUEST";
export const DELETE_TERMS_SUCCESS = "DELETE_TERMS_SUCCESS";
export const DELETE_TERMS_FAILURE = "DELETE_TERMS_FAILURE";

// GMaps Leads
export const FETCH_GMAPS_LEADS_REQUEST = "FETCH_GMAPS_LEADS_REQUEST";
export const FETCH_GMAPS_LEADS_SUCCESS = "FETCH_GMAPS_LEADS_SUCCESS";
export const FETCH_GMAPS_LEADS_FAILURE = "FETCH_GMAPS_LEADS_FAILURE";

export const UPDATE_GMAPS_LEAD_STATUS_REQUEST = "UPDATE_GMAPS_LEAD_STATUS_REQUEST";
export const UPDATE_GMAPS_LEAD_STATUS_SUCCESS = "UPDATE_GMAPS_LEAD_STATUS_SUCCESS";
export const UPDATE_GMAPS_LEAD_STATUS_FAILURE = "UPDATE_GMAPS_LEAD_STATUS_FAILURE";

export const FETCH_GMAPS_LEADS_STATS_SUCCESS = "FETCH_GMAPS_LEADS_STATS_SUCCESS";
export const FETCH_GMAPS_LEADS_DISTINCTS_SUCCESS = "FETCH_GMAPS_LEADS_DISTINCTS_SUCCESS";

export const SET_GMAPS_LEAD_IMPORT = "SET_GMAPS_LEAD_IMPORT";

// Author Master
export const FETCH_AUTHORS_REQUEST = "FETCH_AUTHORS_REQUEST";
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS";
export const FETCH_AUTHORS_FAILURE = "FETCH_AUTHORS_FAILURE";

export const SEARCH_AUTHORS_REQUEST = "SEARCH_AUTHORS_REQUEST";
export const SEARCH_AUTHORS_SUCCESS = "SEARCH_AUTHORS_SUCCESS";
export const SEARCH_AUTHORS_FAILURE = "SEARCH_AUTHORS_FAILURE";

export const CREATE_AUTHOR_REQUEST = "CREATE_AUTHOR_REQUEST";
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const CREATE_AUTHOR_FAILURE = "CREATE_AUTHOR_FAILURE";

export const UPDATE_AUTHOR_REQUEST = "UPDATE_AUTHOR_REQUEST";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_FAILURE = "UPDATE_AUTHOR_FAILURE";

export const DELETE_AUTHOR_REQUEST = "DELETE_AUTHOR_REQUEST";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAILURE = "DELETE_AUTHOR_FAILURE";
export const CLEAR_GMAPS_LEAD_IMPORT = "CLEAR_GMAPS_LEAD_IMPORT";

// Search requests created from an empty search result page
export const INITIALIZE_SEARCH_REQUEST_FORM = "INITIALIZE_SEARCH_REQUEST_FORM";
export const SET_SEARCH_REQUEST_FIELD = "SET_SEARCH_REQUEST_FIELD";
export const RESET_SEARCH_REQUEST_FORM = "RESET_SEARCH_REQUEST_FORM";
export const CREATE_SEARCH_REQUEST_REQUEST = "CREATE_SEARCH_REQUEST_REQUEST";
export const CREATE_SEARCH_REQUEST_SUCCESS = "CREATE_SEARCH_REQUEST_SUCCESS";
export const CREATE_SEARCH_REQUEST_FAILURE = "CREATE_SEARCH_REQUEST_FAILURE";
export const FETCH_SEARCH_REQUESTS_REQUEST = "FETCH_SEARCH_REQUESTS_REQUEST";
export const FETCH_SEARCH_REQUESTS_SUCCESS = "FETCH_SEARCH_REQUESTS_SUCCESS";
export const FETCH_SEARCH_REQUESTS_FAILURE = "FETCH_SEARCH_REQUESTS_FAILURE";
export const FETCH_SEARCH_REQUEST_REQUEST = "FETCH_SEARCH_REQUEST_REQUEST";
export const FETCH_SEARCH_REQUEST_SUCCESS = "FETCH_SEARCH_REQUEST_SUCCESS";
export const FETCH_SEARCH_REQUEST_FAILURE = "FETCH_SEARCH_REQUEST_FAILURE";
export const UPDATE_SEARCH_REQUEST_REQUEST = "UPDATE_SEARCH_REQUEST_REQUEST";
export const UPDATE_SEARCH_REQUEST_SUCCESS = "UPDATE_SEARCH_REQUEST_SUCCESS";
export const UPDATE_SEARCH_REQUEST_FAILURE = "UPDATE_SEARCH_REQUEST_FAILURE";
export const DELETE_SEARCH_REQUEST_REQUEST = "DELETE_SEARCH_REQUEST_REQUEST";
export const DELETE_SEARCH_REQUEST_SUCCESS = "DELETE_SEARCH_REQUEST_SUCCESS";
export const DELETE_SEARCH_REQUEST_FAILURE = "DELETE_SEARCH_REQUEST_FAILURE";
